### ISSUE TITLE
AWS AppSync LogConfig Not Working

### ISSUE THREAD

**Issue by mode2ryan** [sid88in/serverless-appsync-plugin#100]
I added the logConfig into my appSync yml block. When I run `sls deploy-appsync -v` or `sls update-appsync -v` it's not applying the role.
```
appSync:
    name: ${self:service}-${self:provider.stage}-api
    apiId: 1234
    logConfig:
      loggingRoleArn: "arn:aws:iam::12345:role/my-logging-role"
      level: ALL
```
I confirmed that my role is valid yet, the deployments do not enable the logging setting on the AWS AppSync console.

Is there a setting that I'm missing to enable logs? It's a hassle having to manually set the `enable logs` setting on my AWS AppSync API each time I run an `update-appsync` command in the terminal.
