### ISSUE TITLE
Resolver for Specific Schema Field

### ISSUE THREAD

**Issue by jcouser** [sid88in/serverless-appsync-plugin#110]
I've recently been exploring appsync along with this plugin and have just about everything working via serverless, but was unsure if this is possible.

I'm attempting to attach a request/response mapping to a specific field of a given graphql schema object.  For example company.employees.  At the moment the only way I'm seeing to solve this is via the AppSync UI and clicking attach under the given schema field, and forced to create the new mapping via the console.

I'm hoping there's something I'm missing when defining the mappings that do not relate to a given Query or Mutation, but are only related to a schema field.

Thanks in advance!

**Comment by mbelles** [comment]
Great question. How does one define schema field resolvers, via the `serverless.yml` file? All examples seem to point to using the AWS console, which negates the entire point of using `serverless deploy`.

**Comment by Gbahaa** [comment]
Sorry, I may not understood your question well. However, if you have a type `company` in your schema that has a field called `employees`, you can add a mapping template as follows (type can be any type of your schema; not only Query or Mutation)
```
custom:
  accountId: xxxx
  appSync:
    name:  xxx
    mappingTemplates: 
      - dataSource: YOUR_RESOLVER_NAME
        type: company
        field: employees
        request: "YOUR_REQUEST_TEMPLATE.txt"
        response: "YOUR_RESPONSE_TEMPLATE.txt"
```

I prefer, however, to separate mapping-templates in a separate file mapping-template.yml and use it in serverless.yml 
`    mappingTemplates: ${file(mappingTemplates.yml)} 
`
