### ISSUE TITLE
AppSync on existing dynamodb Table

### ISSUE THREAD

**Issue by mlecoq** [sid88in/serverless-appsync-plugin#115]
Hi,

I have a table in production and I would like to plugin appsync on it. 

In configuration, the only way to add one dynamodb datasource is to define it as a resource. 

Logically, when I define my existing table as a resource, I have the following error : _Table_ already exists. 

Is there any way to add an existing table in app sync configuration ? 

I could create a lambda to query the table but it is less convenient than just adding dynamodb resource in yml file.

**Comment by adamthewan** [comment]
Would love this too

**Comment by nakulp007** [comment]
+1

**Comment by bboure** [comment]
@mlecoq Have you tried just setting the name and the region of the table?

````yml
    dataSources:
      - type: AMAZON_DYNAMODB
        name: myDataSource
        config:
          tableName: myTableName
          region: 'us-east-1' # or just leave empty if it is the same as your default
````
And skip defining it in the "resource" part.
That should work.
