### ISSUE TITLE
Best way to handle dynamodb batch operations?

### ISSUE THREAD

**Issue by ack210** [sid88in/serverless-appsync-plugin#120]
AppSync resolvers for batch operations are different than their single-item counterparts in that the mapping template itself requires the dynamodb table name, rather than relying on the datasource.  For apps with "hardcoded" dynamodb table names this isn't a big deal, but for apps that e.g. rely on CloudFormation to name their tables for them, this becomes a bit of an issue.  (One motivation I can think of for not hardcoding the table names is for apps that might use the same account for different stages and therefore would want to include the stage in the dynamodb table name, e.g. MyTable-dev, MyTable-prod).

Are there any suggestions for how to use mapping templates for batch operations with this plugin without having to hardcode the table name in the mapping template itself?

More info on AppSync mapping templates with batch operations: https://docs.aws.amazon.com/appsync/latest/devguide/tutorial-dynamodb-batch.html

And an example batch mapping request template (note the hardcoded table name "Posts"):

```
#set($postsdata = [])
#foreach($item in ${ctx.args.posts})
    $util.qr($postsdata.add($util.dynamodb.toMapValues($item)))
#end

{
    "version" : "2018-05-29",
    "operation" : "BatchPutItem",
    "tables" : {
        "Posts": $utils.toJson($postsdata)
    }
}
```

**Comment by stock1232** [comment]
Could you put a ref: to the logical id of the table to retrieve its name which would be set in the resources section as something like 
logicalIDTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: Table${self:custom.myStage}

where self:custom.myStage is their a default stage or taken from the command line?

Therefore in your mapping template  would look like this 

"tables" : {
        "Ref: logicalIDTable": $utils.toJson($postsdata)
    }

Does this work?

**Comment by bboure** [comment]
@ack210  @stock1232 I am not sure this will work as templates are not interpreted by CloudFormation but pushed as is in Appsync. And I don't believe AppSync supports References.
My recommendation would be to use some kind of template system like https://github.com/janl/mustache.js
The plugin could then accept variables for the table names:

````yml
  - dataSource: myDataSource
    type: Query
    field: field
    requestTemplate:
      template: "request-template.vtl"
      variables:
        table1Name: ${self:provider.stage}-Table1
        table2Name: ${self:provider.stage}-Table2
    response: "response-template.vtl"
````

Also, I don't think this solution would work with `Ref` because this would have to be executed before CloudFormation runs (to send a "compiled" template to CloudFormations). In other words, this would not work:

````yml
  - dataSource: myDataSource
    type: Query
    field: field
    requestTemplate:
      template: "request-template.vtl"
      variables:
        table1Name: Ref: table1Id
        table2Name: Ref: table2Id
    response: "response-template.vtl"
````

What could be done to make this work would be to invoke the AWS api from the plugin to resolve the table name beforehand...

None of this is currently supported but any PR is welcome :)
