### ISSUE TITLE
Make Request & Response Mapping Template extension from .txt to .vtl

### ISSUE THREAD

**Issue by deadcoder0904** [sid88in/serverless-appsync-plugin#123]
`.txt` is for text files but it makes sense to make the `example` in the project change the extension to `.vtl` because it is using Velocity Template Language.

Benefits might be if someone in future makes a extension for Syntax Highlighting, it would be much simpler to detect all `.vtl` files & apply the extension on `.vtl` file rather than a `.txt` file.

This change does not have a significant impact but it makes sense like it does for GraphQL files (`.gql` extension). What do ya'll think❓

**Comment by Jhorlin** [comment]
@deadcoder0904 you can use any extension you wish and this plugin will work. I am currently using vscode with the plug in [vscode-velocity](https://marketplace.visualstudio.com/items?itemName=sodatea.velocity). I get Syntax Highlighting. In your serverless.yml you can simply
```yml
mappingTemplates:
      - dataSource: myDataSource
        type: Mutation
        field: mutationField
        request: request.vtl
        response: response.vtl
```
