### ISSUE TITLE
Data Source Type not supported: 'HTTP

### ISSUE THREAD

**Issue by fgiarritiello** [sid88in/serverless-appsync-plugin#129]
I followed the docs to use HTTP data source but I'm getting `Data Source Type not supported: 'HTTP` error when deploying with serverless. Is this not supported yet?

**Comment by sid88in** [comment]
is this feature supported in appsync? @nealclark can you please help look into this?
reference: https://github.com/sid88in/serverless-appsync-plugin/pull/121

**Comment by fgiarritiello** [comment]
Yes it is implemented in appsync: https://docs.aws.amazon.com/appsync/latest/devguide/tutorial-http-resolvers.html

**Comment by sid88in** [comment]
can you try to build this locally in your aws environment? If the mapping templates are configured correctly then it should probably work (I haven't tried running it).

**Comment by fgiarritiello** [comment]
I think the problem is in the serverless-appsync-plugin version I'm using (1.0.1) which doesn't seem to have the HTTP implementation. What version should I be using for the latest?

**Comment by sid88in** [comment]
Im planning to do a new release version in like few minutes.

**Comment by fgiarritiello** [comment]
Thanks, I appreciate it. Also in the next few days I might be able to help with some contribution if it's still needed. Right now I'm too busy at work.

**Comment by nealclark** [comment]
The feature is supported in appsync and I have used it to create and map an http endpoint.

```yaml
  dataSources:
    - type: HTTP
      name: ChuckNorrisAPI
      description: Connection to Chuck Norris Api
      config:
        endpoint: https://api.icndb.com
  mappingTemplates:
    - dataSource: ChuckNorrisAPI
      type: Query
      field: getJoke
      request: getJoke-request.vm
      response: getJoke-response.vm
```

```vm
// getJoke-request.vm
{
    "version": "2018-05-29",
    "method": "GET",
    "resourcePath": "/jokes/random"
}

// getJoke-response.vm
## if the response status code is not 200, then return an error. Else return the body **
#if($ctx.result.statusCode == 200)
    ## If response is 200, return the body.
    $util.toJson($util.parseJson($context.result.body).value)
#else
    ## If response is not 200, append the response to error block.
    $utils.appendError($ctx.result.body, $ctx.result.statusCode)
#end
```

```graphql
type Query {
  getJoke: Joke
}

type Joke {
  id: Int
  joke: String
}

```
