### ISSUE TITLE
The CloudFormation template is invalid

### ISSUE THREAD

**Issue by xriu** [sid88in/serverless-appsync-plugin#136]
Hello,

Anyone have an idea why I'm getting this error ? I'm using serverless-appsync-plugin with java8

Error
The CloudFormation template is invalid: Template error: instance of Fn::GetAtt references undefined resource GraphqlLambdaFunction

```
provider:
  name: aws
  runtime: java8
  memorySize: 256
  timeout: 60
  stage: staging
  cfLogs: true
  region: eu-west-1
  tracing: true
  logRetentionInDays: 7
  reservedConcurrency: 50

custom:
  accountId: ${env:AWS_ACCOUNT_ID}
  stage: ${opt:stage, self:provider.stage}
  region: ${opt:region, self:provider.region}
....
  appSync:
    name: ${self:custom.service}-${self:custom.stage}-api
    authenticationType: API_KEY
    mappingTemplates:
      - dataSource: awsLambdaDataSource
        type: Query
        field: comments
        request: "comments-request.txt"
        response: "comments-response.txt"
    schema:
    serviceRole: "AppSyncServiceRole"
    dataSources:
      - type: AWS_LAMBDA
        name: awsLambdaDataSource
        description: 'Lambda DataSource'
        config:
          lambdaFunctionArn: { Fn::GetAtt: [GraphqlLambdaFunction, Arn] }
          serviceRoleArn: { Fn::GetAtt: [AppSyncLambdaServiceRole, Arn] }
```

Thanks.

**Comment by bboure** [comment]
@xriu is that your full serverless.yml file?
Looks like you not defining the function called `graphql`

you should have something in your yml that looks like this:

````yml
functions:
  graphql:
    name: functionName
    handler: functions/functionNale.handler
````

Note the `graphql` yml key here. It will result in `GraphqlLambdaFunction` as resource reference in Cloudformations for you function.
which you then can use as you did
````yaml
lambdaFunctionArn: { Fn::GetAtt: [GraphqlLambdaFunction, Arn] }
````

Look [here](https://github.com/serverless/serverless/blob/master/docs/providers/aws/guide/resources.md) in the table.
