### ISSUE TITLE
Automatic serviceRoleArn ?

### ISSUE THREAD

**Issue by bboure** [sid88in/serverless-appsync-plugin#139]
Hi,

I was wondering if we should implement a way to auto-generate the `serviceRole` for each data source when needed. Or at least, to simplify it.
Having to manually define a Service Role for your datasources and reference it in `serviceRoleArn` can be a real pain. 
Especially if you want to create 1 different Role for each data source (which should be the recommended way).
The advantage of this would be that each data source would have the strict minimum privileges required.

My idea was the following: 

- Option 1: You don't specify anything about the role.
The plugin would generate a default Role for the given role type.

e.g: the dateSource type is `AWS_LAMBDA`. The generated Role could be something like:
````yml
Effect: "Allow"
Action:
  - "lambda:invokeFunction"
Resource:
    - "arn:aws:lambda:{stackRegion}:{accountId}:function:myFucntion",
    - "arn:aws:lambda:{stackRegion}:{accountId}:function:myFucntion:*"
````
Where `myFucntion` is the lambda function used for this data source.

- Option 2: You specify a custom policy in a simplified way [just like for your lambdas](https://serverless.com/framework/docs/providers/aws/guide/functions#permissions)

````yml
- type: AWS_LAMBDA
    name: sourceName
    config:
      lambdaFunctionArn: { Fn::GetAtt: [GetTripLambdaFunction, Arn] }
      iamRoleStatements:
        - Effect: Allow
          Action:
        	- lambda:invokeFunction
          Resource: 
            - "arn:aws:lambda:{stackRegion}:{accountId}:function:myFucntion",
            - "arn:aws:lambda:{stackRegion}:{accountId}:function:myFucntion:*"
````

This option is for more fine-grained control on the Policy. For example for DynamoDb data sources, you could specify the `dynamodb:Query` Acition only (By default it would be all actions).

- Option 3: Same as now, you can specify a `serviceRoleArn`

If I find some time, I would be OK suggesting a PR for this but I'd like to have some opinions first.
