### ISSUE TITLE
route not found

### ISSUE THREAD

**Issue by SET001** [sid88in/serverless-appsync-plugin#145]
I'm trying to use this plugin and currenlty have no luck with it.
this is what I have in `serverless.yml` in appSync section:

```
  appSync:
    name: test
    authenticationType: API_KEY
    serviceRole: "AppSyncServiceRole"
    mappingTemplates:
      - dataSource: Subscriber
        type: Mutation
        field: createSubscriber
        request: createSubscriberRequest.txt
        response: createSubscriberResponse.txt
    dataSources:
      - type: AMAZON_DYNAMODB
        name: Subscriber
        description: 'Subscribers table'
        config:
          tableName: ens-subscribers-${self:provider.stage}
```
So I expect to be able to do a createSubscriber mutation using GraphQL Playground.

When I'm running `serverless offline start` Im gettin `Serverless: Offline listening on http://localhost:3000`
But when I do GET to localhost:3000 I'm getting such a response

`{"statusCode":404,"error":"Serverless-offline: route not found.","currentRoute":"get - /","existingRoutes":[]}`

What am I missing?
