### ISSUE TITLE
Feature Request/Discussion: Support for multiple APIs

### ISSUE THREAD

**Issue by ZY-Ang** [sid88in/serverless-appsync-plugin#154]
Currently, the plugin only allows the deployment of a single AppSync API via the appSync map:
``` yaml
custom:
  appSync:
    name: all-in-one-appsync-endpoint-yikes
    schema: AppSync/schema.graphql
    authenticationType: OPENID_CONNECT
    openIdConnectConfig:
    ...
    serviceRole: AllInOneServiceRole
    dataSources:
    ...
    mappingTemplatesLocation: ...
    mappingTemplates:
    ...
```

What Multiple APIs might look like:
```yaml
custom:
  appSync:
    - name: authenticated-appsync-endpoint
      schema: AppSync/schema.graphql # or something like AppSync/private/schema.graphql
      authenticationType: OPENID_CONNECT
      openIdConnectConfig:
      ...
      serviceRole: AuthenticatedAppSyncServiceRole
      dataSources:
      ...
      mappingTemplatesLocation: ...
      mappingTemplates:
      ...
    - name: public-appsync-endpoint
      schema: AppSync/schema.graphql # or something like AppSync/public/schema.graphql
      authenticationType: NONE # or API_KEY, you get the idea
      serviceRole: PublicAppSyncServiceRole
      dataSources:
      ...
      mappingTemplatesLocation: ...
      mappingTemplates:
      ...
```

Reasons:
1. The issue resolution [here](https://github.com/sid88in/serverless-appsync-plugin/issues/135) does not play well with the sharing of datasources and functions across multiple separate services. I would have to duplicate an entire service and all its dependencies just to create a "public" version of the API.
2. Given that the public version of the API would most likely be a subset of the private/authenticated API, it would make sense to update them together, so that we can control authentication via resolver templates, while sharing a single API schema, should we so choose.
3. Splitting authenticated/public fields to separate APIs or services defeats the purpose of GraphQL as I would now have multiple endpoints, and have to instantiate multiple GraphQL clients.
