### ISSUE TITLE
"No resolver found" issues

### ISSUE THREAD

**Issue by rarbo** [sid88in/serverless-appsync-plugin#158]
We've setup a basic graphql schema and deployed it using serverless. After playing around with the schema (tweaking and testing some queries via the AWS console) we started getting these errors on subsequent deployments:

An error occurred: GraphQlResolverMutationcreateAccount - No resolver found. (Service: AWSAppSync; Status Code: 404; Error Code: NotFoundException; Request ID: d46415fb-c6d6-11e8-8151-61272b94e470).

This issue is similar to https://github.com/sid88in/serverless-appsync-plugin/issues/101. However Im unable to fix the issue following the suggestions in this issue.

**Comment by bboure** [comment]
Hi @rarbo usually you should never touch things manually in AWS console as it could always break and make things out of sync with your template.
Now, I understand that you are still playing with it and testing it. (Don't worry, I do that too 😄)

First off, did you change something in your serverlesss.yml after doing those changes on AWS?
This error is returned by AWS cloudformation and it looks like maybe your template is trying to use a resolver that was not defined. Did you rename a resolver and maybe forgot to change the reference in the appsync datasource?

If you can, could you share your serverless template, that could help understanding the issue.

**Comment by rarbo** [comment]
Hi @bboure 

Thanks for the reply. 

After playing around with some of the template mappings and removing resolvers via the console, we decided to add a bunch of new mappings via the serverless.yml.

Is there a way to force cloudformation to disregard the current AppSync setup and deploy all changes again via the deployment?

Going forward we've learnt our lesson and wont be making direct changes via the console 😆 

serverless.yml below (as background, we're just playing around with a proof of concept atm):
```
tenant: pservices
app: services
service: p-services

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-sentry
  - serverless-domain-manager
  - serverless-appsync-plugin
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${self:custom.stage}
  region: us-west-2

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      # Restrict our IAM role permissions to
      # the specific table for the stage
      Resource:
        - "Fn::GetAtt": [AccountTable, Arn]

package:
  exclude:
    - services/**/*.test.js
    - .git/**
    - coverage/**
    - env.yml
    - node_modules/serverless

# serverless-webpack configuration
# Enable auto-packing of external modules
custom:
  stage: ${opt:stage, 'dev'} # Set the default stage used. Default is dev
  configFile: ${file(config/config.yml):${self:custom.stage}} # Passes the current stage to the config file
  customDomain:
    domainName: ${self:custom.configFile.DOMAIN}
    stage: ${self:custom.stage}
    certificateName: "pservices.com"
    createRoute53Record: true
  # Set our DynamoDB throughput for prod and all other non-prod stages.
  tableThroughputs:
    prod: 5
    default: 1
  tableThroughput: ${self:custom.tableThroughputs.${self:custom.stage}, self:custom.tableThroughputs.default}
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  # https://github.com/arabold/serverless-sentry-plugin
  sentry:
    dsn: https://xxxxxxx@sentry.io/1284726
    organization: pservices
    project: p-services
    authToken: xxxxxx
    release:
      version: git
  appSync:
    name: pservices-${self:custom.stage}-api
    authenticationType: AMAZON_COGNITO_USER_POOLS
    userPoolConfig:
      awsRegion: us-west-2
      defaultAction: ALLOW
      userPoolId: { Ref: CognitoUserPool }
    mappingTemplates:
      #Dynamo Account Table - Get Account - Query + Payload
      - dataSource: DynamoAccounts
        type: Query
        field: account
        request: "account-request.vtl"
        response: "account-response.vtl"
      - dataSource: DynamoAccounts
        type: AccountPayload
        field: account
        request: "common-payloadrelay-request.vtl"
        response: "common-payloadrelay-response.vtl"
      #Dynamo Account Table - Get All Accounts - Query + Payload
      - dataSource: DynamoAccounts
        type: Query
        field: allAccounts
        request: "allAccounts-request.vtl"
        response: "allAccounts-response.vtl"
      - dataSource: DynamoAccounts
        type: AllAccountsPayload
        field: accounts
        request: "common-payloadrelay-request.vtl"
        response: "common-payloadrelay-response.vtl"
      #Dynamo Account Table - Create Account - Mutation + Payload
      - dataSource: DynamoAccounts
        type: Mutation
        field: createAccount
        request: "createAccount-request.vtl"
        response: "createAccount-response.vtl"
      - dataSource: DynamoAccounts
        type: CreateAccountPayload
        field: account
        request: "common-payloadrelay-request.vtl"
        response: "common-payloadrelay-response.vtl"
    schema: # defaults schema.graphql
    serviceRole: "AppSyncServiceRole"
    dataSources:
      - type: NONE
        name: PayloadRelay
        description: "Payload relay"
      - type: AMAZON_DYNAMODB
        name: DynamoAccounts
        description: "Accounts table"
        config:
          tableName:
            Ref: AccountTable
          serviceRoleArn: { Fn::GetAtt: [AppSyncDynamoServiceRole, Arn] }
      - type: AWS_LAMBDA
        name: LambdaSource
        description: "Lambda DataSource"
        config:
          lambdaFunctionArn: { Fn::GetAtt: [GraphqlLambdaFunction, Arn] } # Where GraphqlLambdaFunction is the lambda function cloudformation resource created by serverless for the serverless function named graphql
          serviceRoleArn: { Fn::GetAtt: [AppSyncLambdaServiceRole, Arn] }
functions:
  graphql:
    handler: services/graphql/handler.graphql

resources:
  # DynamoDB
  - ${file(resources/dynamodb-table.yml)}
  # Cognito
  - ${file(resources/cognito-user-pool.yml)}
  - ${file(resources/cognito-identity-pool.yml)}
```

**Comment by bboure** [comment]
@rarbo issue should be around here
````yml
     - dataSource: DynamoAccounts
        type: Mutation
        field: createAccount
        request: "createAccount-request.vtl"
        response: "createAccount-response.vtl"
      - dataSource: DynamoAccounts
        type: CreateAccountPayload
        field: account
        request: "common-payloadrelay-request.vtl"
        response: "common-payloadrelay-response.vtl"
```

DO you actually have a Mutation field called `createAccount` and  type called `CreateAccountPayload` with an `account` field in your `schema.graphql` file?
