### ISSUE TITLE
How can I get the graphqlApiId for iamRoleStatements

### ISSUE THREAD

**Issue by adrianhall** [sid88in/serverless-appsync-plugin#160]
The ARN for the GraphQL API needs to be included in IAM role statements.  example:

```
    AuthRole:
      Type                                : AWS::IAM::Role
      Description                         : "Role that the an authenticated user assumes"
      Properties:
        RoleName                          : ${self:provider.apiname}-auth
        AssumeRolePolicyDocument:
          Version                         : "2012-10-17"
          Statement:
            - Effect                      : Allow
              Principal:
                Federated                 : cognito-identity.amazonaws.com
              Action                      : sts:AssumeRoleWithWebIdentity
              Condition:
                ForAnyValue:StringLike:
                  "cognito-identity.amazon.com:amr": "authenticated"
        Policies:
          - PolicyName                    : ${self:provider.apiname}-auth-appsync
            PolicyDocument:
              Version                     : "2012-10-17"
              Statement:
                - Effect                  : Allow
                  Action                  : appsync:GraphQL
                  Resource:
                    - "arn:aws:appsync:${self:custom.region}:#{AWS::AccountId}:apis/GRAPHQL-APIID/types/Query/fields/allUsers"
```

Note the `GRAPHQL-APIID`.  This is the Api ID for the GraphQL service and is only available after the GraphQL API is deployed.  

I can (obviously) replace this with * and it will usually work, but it isn't really "best practice" (least permissions).  

How can I include the GraphQL API ID in other dependent parts of the resources, IAM roles, etc.?

**Comment by bboure** [comment]
@adrianhall You should be able to get it by using 

````yml
Fn::GetAtt:
  - GraphQlApi
  - ApiId
````

I think this should work too:

````yml
Ref: GraphQlApi
````

But it looks like what you need is the Arn for the policy, so you might just be good doing
````yml
Policies:
          - PolicyName                    : ${self:provider.apiname}-auth-appsync
            PolicyDocument:
              Version                     : "2012-10-17"
              Statement:
                - Effect                  : Allow
                  Action                  : appsync:GraphQL
                  Resource:
					- Fn::GetAtt:
					  - GraphQlApi
					  - Arn

````


What are you trying to achieve here. I don't think that cognito needs an explicit role for accessing the AppSync Api...
