### ISSUE TITLE
multiple lambda data sources

### ISSUE THREAD

**Issue by stock1232** [sid88in/serverless-appsync-plugin#172]
Is it possible to have multiple lambda data sources with this plugin? Would the yml config be something like this?

functions:
  graphql:
    handler: handler.getTweeterFeed
    handler: handler.getAnotherFeed

if so how is the datasource ARN impacted?

 dataSources:
      - type: AWS_LAMBDA
        name: awsLambdaDataSource
        description: 'Lambda DataSource'
        config:
          lambdaFunctionArn: { Fn::GetAtt: [GraphqlLambdaFunction, Arn] } # Where GraphqlLambdaFunction is the lambda function cloudformation resource created by serverless for the serverless function named graphql
          serviceRoleArn: { Fn::GetAtt: [AppSyncLambdaServiceRole, Arn] }

What would I have to add to my service role policy resource?

   Resource:
                    - "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-dev-graphql"
                    - "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-dev-graphql:*"

**Comment by bboure** [comment]
@stock1232 
Yes, it is possible to have several data sources using different or the same Lambdas. 

Just pass them as an array:

````yml
dataSources:
  - type: AWS_LAMBDA
    name: lambdaSource1
    description: 'Description'
    config:
      lambdaFunctionArn: { Fn::GetAtt: [YourLambdaFunction, Arn] }
  - type: AWS_LAMBDA
    name: lambdaSource2
    description: 'Whatever'
    config:
      lambdaFunctionArn: { Fn::GetAtt: [YourOtherLambdaFunction, Arn] }
````

Concerning the Service Role, you have nothing to do, the plugin will make one for you by default. And allow execution of your lambda and its Aliases (exactly as you should in your question).
