### ISSUE TITLE
missing path

### ISSUE THREAD

**Issue by stock1232** [sid88in/serverless-appsync-plugin#173]
I am trying to follow the config for dynamobd and lamdba. I am using webpack plugin to bundle my lamdba function but I am getting this error rimraf: missing path

it seems it can't find my entry point

Versions 
    "serverless-webpack": "^5.2.0",
    "webpack": "^4.25.1",
    "webpack-node-externals": "^1.6.0"

Relevant parts of my config

Webpack (just like the example)

const slsw = require('serverless-webpack');
const nodeExternals = require('webpack-node-externals');
const path = require('path');

```
module.exports = {
  mode: "development",
  entry: slsw.lib.entries,
  target: "node",
  output: {
    libraryTarget: 'commonjs',
    publicPath: path.join(__dirname, '.webpack/'),
    filename: '[name].js'
    },
  // Since 'aws-sdk' is not compatible with webpack,
  // we exclude all node dependencies
  externals: [nodeExternals()],
  // Run babel on all .js files and skip those in node_modules
  module: {
    rules: [
      {
        test: /\.js$/,
        use: [
          {
        loader: "babel-loader"
          }
        ],
        include: __dirname,
        exclude: /node_modules/
      }
    ]
  }
};
```

serverless yml

```
service: lifting-bro-api

frameworkVersion: ">=1.21.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
  profile: ServiceAccountBeta
  

plugins:
  - serverless-appsync-plugin
  - serverless-webpack

functions:
  graphql:
    handler: handler.getExerciseList
```

in the main directory i have handle.js file with a export named getExerciseList. It just returns a static list from a seperate required file in the same directory. 

```
const elist = require('./list.js');

  

exports.getExerciseList = async (event) => {
  console.log("Received event {}", JSON.stringify(event, 3));
 
      switch(event.field) {
        case "getExerciseList":
        return elist;
        default:
          return "Unknown field, unable to resolve";
      }
    
};
```
