### ISSUE TITLE
userPoolConfig in different region does not work

### ISSUE THREAD

**Issue by asnaseer-resilient** [sid88in/serverless-appsync-plugin#178]
We have a **serverless.yml** file that deploys AppSync in **eu-west-1** region and uses a user pool that resides in **eu-west-2** region. A snippet of our **serverless.yml** file:

```
service: todos

frameworkVersion: ">=1.21.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-west-1

plugins:
- serverless-appsync-plugin

custom:
  accountId: XXX-hidden-XXX

  appSync:
    name: ${self:service}
    authenticationType: AMAZON_COGNITO_USER_POOLS
    userPoolConfig:
      region: eu-west-2
      awsRegion: eu-west-2
      defaultAction: ALLOW
      userPoolId: XXX-hidden-XXX
    mappingTemplates:
      ...
```
where **XXX-hidden-XXX** are just markers for information that we do not wish to reveal.

Is this a know issue or do we have a mis-configuration in our **serverless.yml** file?
