### ISSUE TITLE
Plugin should resolve variables and pseudo parameters

### ISSUE THREAD

**Issue by majorgilles** [sid88in/serverless-appsync-plugin#191]
When using the following config object and plugins:
```yaml
plugins:
  - serverless-appsync-plugin
  - serverless-pseudo-parameters

config:
          endpoint: ${self:custom.elasticSearch.arn}
```
the literal string with pseudo parameters is passed to the endpoint property.
other plugins resolve such variables correctly.

**Comment by sid88in** [comment]
This is resolved on v2, and you no longer need `serverless-pseudo-parameters` (it's obsolete —
Serverless v3, which v2 requires, supports CloudFormation pseudo-parameters and intrinsics in
variables natively).

For passthrough values like a data source `endpoint`, just use a native intrinsic and the
plugin forwards it to the template:

```yml
config:
  endpoint: { Fn::Sub: 'https://search-${AWS::Region}...' }
  # Ref / Fn::GetAtt / Fn::ImportValue all work too
```

The endpoint field (and most ARN/region/name fields) accept intrinsic functions directly, so
there's no `#{...}` transform step to get out of order. Closing as resolved in v2.
