### ISSUE TITLE
"Error: Log group not found" with logConfig enabled

### ISSUE THREAD

**Issue by christiankaindl** [sid88in/serverless-appsync-plugin#195]
Hey there!

I want to enable logging in my project. I included the `logConfig` as seen in the serverless-appsync-plugin README (my AppSync config is below). Everything is fine and it also deploys without errors.

The problem begins when I try to check the 'Logs' checkbox and run a query in the AWS AppSync Query Dashboard:

![logging](https://user-images.githubusercontent.com/15364860/50539074-5ca8e900-0b7a-11e9-9405-88a5237d9a1a.png)

When I click on 'View in Cloudwatch' this shows up:

![logging2](https://user-images.githubusercontent.com/15364860/50539084-764a3080-0b7a-11e9-99a0-5d393beb7b48.png)

It seems like no Log Group is being created, but I have no idea why. I looked at the existing GitHub issues in the serverless-appsync-plugin repo and also searched online for example projects to look how they enable logging, but couldn't resolve the issue.

---

My AppSync configuration is the following:

``` yaml
appSync:
    name: ${self:custom.stage}-api
    authenticationType: AMAZON_COGNITO_USER_POOLS
    userPoolConfig:
      awsRegion: ${self:provider.region}
      defaultAction: ALLOW
      userPoolId: { Ref: CognitoUserPool }
    mappingTemplatesLocation: mapping-templates
    logConfig:
      loggingRoleArn: { Fn::GetAtt: [AppSyncLoggingServiceRole, Arn] }
      level: ALL
    mappingTemplates:
    .
    .
    .
    dataSources:
    .
    .
    .

```

Where `AppSyncLoggingServiceRole` is from this [Serverless Chat App example](https://github.com/chief-wizard/serverless-appsync-chat-app/blob/master/resources/roles.yml)

Any ideas?

**Comment by christiankaindl** [comment]
I found the issue!

I had a look at the AWS AppSync [Monitoring](https://docs.aws.amazon.com/appsync/latest/devguide/monitoring.html?shortFooter=true#setup-and-configuration) section and noticed that the role I used had the wrong permissions.

So I changed it from

```yaml
      Policies:
        -
          PolicyName: "CloudwatchLogging-${self:service}-Policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action:
                  - "cloudwatch:*"
                Resource:
                  - "*"
```
to the following
``` yaml
      Policies:
        -
          PolicyName: "CloudwatchLogging-${self:service}-Policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource:
                  - "*"
```

I guess the [Serverless Chat App example](https://github.com/chief-wizard/serverless-appsync-chat-app/blob/master/resources/roles.yml), which I copied from in this case, has a bug.

Copy/Pasting aint do it all the time, I guess :P 

Thanks anyway and much love for this awesome plugin!
