### ISSUE TITLE
Resolvers not getting attached

### ISSUE THREAD

**Issue by indeedwatson** [sid88in/serverless-appsync-plugin#225]
Here's the relevant part of my `serverless.yml`

```yml
mappingTemplates:
  - dataSource: WordListResolver
    type: Card
    field: group
    request: "card-group-request.v
    response: "common-response.vtl
  - dataSource: WordListResolver
    type: Card
    field: list
    request: card-list-request.vtl
    response: common-response.vtl

```

And `schema.graphql`

```graphql
schema {
  query: Query
  mutation: Mutation
  subscription: Subscription
}

type Card {
  group: CardGroup!
  id: ID!
  list: CardList!
  phrase: String!
  sentences: [DefinitionSentence]
  translation: String!
}
```

However, when looking at the console:

![image](https://user-images.githubusercontent.com/10749504/54006462-35ebcd80-413c-11e9-8326-c765af795454.png)

Nothing gets attached.
