### ISSUE TITLE
Automatic Role generation not working when endpoint is a reference

### ISSUE THREAD

**Issue by bboure** [sid88in/serverless-appsync-plugin#233]
When passing `endpoint` as a reference from a Resource, this fails:
https://github.com/sid88in/serverless-appsync-plugin/blob/master/index.js#L552

Example:

````yaml
  - type: AMAZON_ELASTICSEARCH
    name: elastic
    config:
      endpoint:
        Fn::Join:
          - ''
          - - https://
            - Fn::GetAtt:
              - ElasticSearchInstance
              - DomainEndpoint
````

This happens in the process of auto-generating the iam Roles and policies, because the regexp receives an object. 

A solution for now is to pass a custom `iamRoleStatements`.

We should see what to do about it.
The very least would be to throw an error specifying that the ES arn cannot be auto-discovered, and therefore must be passed manually through `iamRoleStatements`.

Another, more advanced, solution would be to allow passing the resoruce name of the ES definition and use it to auto-generate both the ARN for the Role and the endpoint for the data source.
Something similar to `functionName` for `AWS_LAMBDA`

````yaml
  - type: AMAZON_ELASTICSEARCH
    name: elastic
    config:
      endpointResourceName: ElasticSearchInstance
````

**Comment by bboure** [comment]
Fixed in #286

**Comment by mfogel** [comment]
@bboure thanks for working on this. But I think there's a bug in the implementation.

I'm trying to use the auto-role generation as enabled by this clause https://github.com/sid88in/serverless-appsync-plugin/pull/286/files#diff-168726dbe96b3ce427e7fedce31bb0bcR642

Here's my data source:

```yml
      - type: AMAZON_ELASTICSEARCH
        name: ElasticSearchDataSource
        config:
          endpoint: {'Fn::GetAtt': [ElasticSearchDomain, DomainEndpoint]}
```

Where `ElasticSearchDomain` is defined to be a `AWS::Elasticsearch::Domain`.

When deploying this, the auto-role generation in this plugin appears to work but AWS returns the error:

```
An error occurred: GraphQlDsElasticSearchDataSource - Property validation failure: [Value for property {/ElasticsearchConfig/Endpoint} does not match pattern {(?i)https?://.*$}].
```

AWS expects `config.endpoint` to begin with `https://`, but `ElasticSearchDomain.DomainEndpoint` does not include the leading `https://`.

However, if I add the leading `https://`...

```yml
      - type: AMAZON_ELASTICSEARCH
        name: ElasticSearchDataSource
        config:
          endpoint: {'Join': ['', ['https://', {'Fn::GetAtt': [ElasticSearchDomain, DomainEndpoint]}]]}
```

Then this auto-role generation throws an error `Could not determine the Arn for dataSource 'ElasticSearchDataSource`  and I have to add my own `iamRoleStatements` stanza so that the custom role generation will be skipped, and I'm able to deploy.

Thoughts? Is there a way to get the auto-role generation working that I'm missing? thanks
