### ISSUE TITLE
RDS not working: "invalid cluster id"

### ISSUE THREAD

**Issue by mogusbi** [sid88in/serverless-appsync-plugin#235]
I am trying to set up AppSync using RDS (Aurora Serverless) as a datasource but I cannot get it working as I'm met with this error on the AppSync console

`ERROR: invalid cluster id: test-develop-aurora-rds`

This is my serverless config

```yaml
service:
  name: test
  publish: false

plugins:
  - serverless-appsync-plugin
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs8.10
  region: ${opt:region, 'us-east-1'} # TODO: Move to eu-west-1 when Data API is available
  stage: ${opt:stage, 'local'}
  environment:
    STAGE: ${self:provider.stage}
    NODE_ENV: ${env:NODE_ENV, 'production'}

custom:
  accountId: #{AWS::AccountId}

  # Used to transform strings for things like Cognito
  transformations:
    develop: Develop
    fcbarcelonaweb: Test

  aurora:
    dbName: application
    host:
      Fn::GetAtt: [AuroraRDSCluster, Endpoint.Address]
    port:
      Fn::GetAtt: [AuroraRDSCluster, Endpoint.Port]

  appSync:
    name: ${self:service}-${self:provider.stage}
    authenticationType: AMAZON_COGNITO_USER_POOLS
    userPoolConfig:
      awsRegion: ${self:provider.region}
      defaultAction: ALLOW
      userPoolId: { Ref: CognitoUserPool }
    mappingTemplatesLocation: src/mapping-templates
    mappingTemplates:
      - dataSource: Database
        type: Query
        field: getArticle
        request: getArticle-request-mapping-template.vtl
        response: getArticle-response-mapping-template.vtl
      - dataSource: Database
        type: Mutation
        field: createArticle
        request: createArticle-request-mapping-template.vtl
        response: createArticle-response-mapping-template.vtl
    schema: src/schema.graphql
    serviceRole: AppSyncServiceRole
    dataSources:
      - type: RELATIONAL_DATABASE
        name: Database
        description: Application database
        config:
          dbClusterIdentifier: { Ref: AuroraRDSCluster }
          awsSecretStoreArn: { Ref: AuroraRotationSecret }
          serviceRoleArn: { Fn::GetAtt: [AuroraRDSServiceRole, Arn] }
          databaseName: ${self:custom.aurora.dbName}
          awsRegion: ${self:provider.region}

resources:
  Resources:
    # Cognito
    CognitoUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: ${self:service}-${self:provider.stage}-user-pool

    CognitoUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: ${self:service}-${self:provider.stage}-client
        UserPoolId:
          Ref: CognitoUserPool

    CognitoIdentityPool:
      Type: AWS::Cognito::IdentityPool
      Properties:
        IdentityPoolName: ${self:custom.transformations.${self:service}}${self:custom.transformations.${self:provider.stage}}IdentityPool
        AllowUnauthenticatedIdentities: false
        CognitoIdentityProviders:
          - ClientId:
              Ref: CognitoUserPoolClient
            ProviderName:
              Fn::GetAtt: [CognitoUserPool, ProviderName]

    CognitoIdentityPoolRoles:
      Type: AWS::Cognito::IdentityPoolRoleAttachment
      Properties:
        IdentityPoolId:
          Ref: CognitoIdentityPool
        Roles:
          authenticated:
            Fn::GetAtt: [CognitoAuthRole, Arn]
          unauthenticated:
            Fn::GetAtt: [CognitoUnauthRole, Arn]

    CognitoAuthRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: ${self:service}-${self:provider.stage}-auth-role
        Path: /
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Federated: cognito-identity.amazonaws.com
              Action:
                - sts:AssumeRoleWithWebIdentity
              Condition:
                StringEquals:
                  "cognito-identity.amazonaws.com:aud":
                    Ref: CognitoIdentityPool
                "ForAnyValue:StringLike":
                  "cognito-identity.amazonaws.com:amr": authenticated
        Policies:
          - PolicyName: CognitoAuthorizedPolicy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - mobileanalytics:PutEvents
                    - cognito-sync:*
                    - cognito-identity:*
                  Resource: '*'
                - Effect: Allow
                  Action:
                    - execute-api:Invoke
                  Resource: '*'

    CognitoUnauthRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: ${self:service}-${self:provider.stage}-unauth-role
        Path: /
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Federated: cognito-identity.amazonaws.com
              Action:
                - sts:AssumeRoleWithWebIdentity
              Condition:
                StringEquals:
                  "cognito-identity.amazonaws.com:aud":
                    Ref: CognitoIdentityPool
                "ForAnyValue:StringLike":
                  "cognito-identity.amazonaws.com:amr": unauthenticated
        Policies:
          - PolicyName: CognitoUnauthorizedPolicy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - mobileanalytics:PutEvents
                    - cognito-sync:*
                    - cognito-identity:*
                  Resource: '*'

    # RDS
    AuroraRDSServiceRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: Aurora-${self:custom.appSync.serviceRole}
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            -
              Effect: Allow
              Principal:
                Service:
                  - appsync.amazonaws.com
              Action:
                - sts:AssumeRole
        Policies:
          -
            PolicyName: Aurora-${self:custom.appSync.serviceRole}-Policy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                -
                  Effect: Allow
                  Action:
                    - rds-data:DeleteItems
                    - rds-data:ExecuteSql
                    - rds-data:GetItems
                    - rds-data:InsertItems
                    - rds-data:UpdateItems
                  Resource: '*'
                    # TODO: Sort out IAM resources for RDS
                    # - arn:aws:rds:${self:provider.region}:#{AWS::AccountId}:cluster:${self:service}-${self:provider.stage}-aurora-rds
                    # - arn:aws:rds:${self:provider.region}:#{AWS::AccountId}:cluster:${self:service}-${self:provider.stage}-aurora-rds:*
                -
                  Effect: Allow
                  Action:
                    - secretsmanager:GetSecretValue
                  Resource:
                    - arn:aws:secretsmanager:${self:provider.region}:#{AWS::AccountId}:secret:${self:service}-${self:provider.stage}-aurora-secret-*

    # TODO: Key rotation lambda
    AuroraRotationSecret:
      Type: AWS::SecretsManager::Secret
      Properties:
        Description: Rotating RDS secrets
        Name: ${self:service}-${self:provider.stage}-aurora-secret
        GenerateSecretString:
          SecretStringTemplate: '{"username": "root"}'
          GenerateStringKey: 'password'
          PasswordLength: 16
          ExcludeCharacters: '"@/\'

    AuroraRDSCluster:
      Type: AWS::RDS::DBCluster
      Properties:
        MasterUsername: !Join ['', ['{{resolve:secretsmanager:', !Ref AuroraRotationSecret, ':SecretString:username}}' ]]
        MasterUserPassword: !Join ['', ['{{resolve:secretsmanager:', !Ref AuroraRotationSecret, ':SecretString:password}}' ]]
        # TODO: Enable when added to CFN
        # EnableHttpEndpoint: true
        DBClusterIdentifier: ${self:service}-${self:provider.stage}-aurora-rds
        Engine: aurora
        EngineMode: serverless
        ScalingConfiguration:
          AutoPause: true
          MaxCapacity: 8
          MinCapacity: 2
        DatabaseName: ${self:custom.aurora.dbName}
        BackupRetentionPeriod: 3

    SecretAuroraRDSClusterAttachment:
      Type: AWS::SecretsManager::SecretTargetAttachment
      Properties:
        SecretId: !Ref AuroraRotationSecret
        TargetId: !Ref AuroraRDSCluster
        TargetType: AWS::RDS::DBCluster
```

This is the GraphQL schema

```
type Mutation {
  createArticle (input: ArticleInput!): Article
}

input ArticleInput {
  content: String!
  link: String!
  publishDate: String!
  title: String!
}

type Query {
  getArticle (id: ID!): Article
}

type Article {
  id: ID!
  content: String!
  link: String!
  publishDate: String!
  title: String!
}

schema {
  query: Query
  mutation: Mutation
}
```

and the mapping templates templates

```
// createArticle-request-mapping-template.vtl
#set($id=$utils.autoId())
{
    "version": "2018-05-29",
    "statements": [
        "INSERT INTO Article VALUES ('$id', '$ctx.args.input.content', '$ctx.args.input.link', '$ctx.args.input.publishDate', '$ctx.args.input.title')",
        "SELECT * FROM Article WHERE id = '$id'"
    ]
}

// createArticle-response-mapping-template.vtl
#if($ctx.error)
    $utils.error($ctx.error.message, $ctx.error.type)
#end

$utils.toJson($utils.rds.toJsonObject($ctx.result)[1][0])

// getArticle-request-mapping-template.vtl
{
  "version" : "2018-05-29",
  "statements": [
    "SELECT * FROM Article WHERE id='$ctx.args.id'"
  ]
}

// getArticle-response-mapping-template.vtl
#if($ctx.error)
    $utils.error($ctx.error.message, $ctx.error.type)
#end

$utils.toJson($utils.rds.toJsonObject($ctx.result)[0][0])

```

I've also gone into the RDS console and enabled the Data API so what am I doing wrong?
