### ISSUE TITLE
Resolver Mappings

### ISSUE THREAD

**Issue by jpstrikesback** [sid88in/serverless-appsync-plugin#25]
Just a quick note to say I'm going to be working on making the resolver mappings a bit more generalized.

Am I right to think that the serverless.yml should drive the resolver mappings? i.e.:

- look for resolver mappings via the mappingTemplates key:
```yaml
mappingTemplates:
  - dataSource: Tweets
    type: User
    field: topTweet
    request: "topTweet-request-mapping-template.txt"
    response: "topTweet-response-mapping-template.txt"
  - dataSource: Users
    type: Query
    field: meInfo
    request: "meInfo-request-mapping-template.txt"
    response: "meInfo-response-mapping-template.txt"
...
```

- createResolver for each discovered mapping
