### ISSUE TITLE
Invalid endpoint configuration when getting attribute from resource

### ISSUE THREAD

**Issue by stephanos199** [sid88in/serverless-appsync-plugin#271]
I'm trying to add an Elasticsearch data source to my project but unless I put in the full URL (which I don't want tot do because I'd like to deploy this in various environments without manual intervention) it doesn't work and it throws the error `Invalid AWS ElasticSearch endpoint: '[object Object]` is there a workaround for this or am I doing something wrong?
```
custom:
  appSync:
    name: [NAME]
    authenticationType: API_KEY
    serviceRole: [SERVICE_ROLE]
    dataSources:
      - type: AMAZON_ELASTICSEARCH
        name: [ES_NAME]
        config:
          endpoint: !Join [ '', ['https://', !GetAtt MyESResource.DomainEndpoint ]]
```

**Comment by bboure** [comment]
@stephanos199 Not sure why it is not working. Might have to do with the special notation using `!`
Try with
````yml
- type: AMAZON_ELASTICSEARCH
    name:[NAME]
    config:
      endpoint:
        Fn::Join:
          - ''
          - - https://
            - Fn::GetAtt:
              - MyESResource
              - DomainEndpoint
````

That works for me.
