### ISSUE TITLE
Multiple schema files using glob path

### ISSUE THREAD

**Issue by aprat84** [sid88in/serverless-appsync-plugin#273]
About what you did in this pull request (https://github.com/sid88in/serverless-appsync-plugin/pull/227) which is a great addition to the plugin, why not take it a step further and also support a glob path? Like so:

```yaml
custom:
  appSync:
    schema: path/to/**/*.graphql
```
