### ISSUE TITLE
Cannot reference API ID

### ISSUE THREAD

**Issue by IanAtDazed** [sid88in/serverless-appsync-plugin#275]
Firstly, I appreciate that this is very similar to [#160](https://github.com/sid88in/serverless-appsync-plugin/issues/160) issue, but whatever I do, I cannot get this to work for me.

I also apologize if this is a little long, but I want to be clear about what I have tried.  

My project is as follows:
### serverless.yml
```
...
custom:
  ...
  myAppSyncApi:
    name: "aws-application-api"
  ...
  appSync:
    - ${file(custom/appsync.yml)}
...
resources:
  # Cognito
  - ${file(resources/cognito.yml)}
```
### appsync.yml
```
name:  ${self:custom.myAppSyncApi.name}
authenticationType: AWS_IAM
mappingTemplates:
  - dataSource: AppItem
    type: Query
    field: listIndicators
    request: "listIndicators-request.vtl"
    response: "listIndicators-response.vtl"
dataSources:
  - type: AMAZON_DYNAMODB
    name: AppItem
    description: 'A single table for the entire application.'
    config:
      tableName: { Ref: dynamoDbAppItem }
      serviceRoleArn: { Fn::GetAtt: [AppSyncdynamoDbAppItemServiceRole, Arn] }
```
When I deploy this, everything builds on the backend as expected.

Now, I need to reference the AppSync API ID in role policies for a Cognito Identity Pool’s Authenticated and Unauthenticated Roles. Basically, I need to programmatically replace [MY API ID] in the code below:
### cognito.yml
```
Resources:
  ...               
  CognitoUnauthRole:
    ...
      Policies:
        - PolicyName: "CognitoUnauthorizedPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
                ...
              - Effect: "Allow"
                Action:
                  - "appsync:GraphQL"
                Resource:
                  Fn::Join:
                    - ""
                    - - "arn:aws:appsync:${self:provider.region}:"
                      - Ref : AWS::AccountId
                      - ":apis/"
                      - "[MY API ID]"
                      - "/types/Query/fields/listEconomicIndicators"
```
### ATTEMPT 1
I gave my appsync code a reference name of myAppSyncApi:
### appsync.yml
```
myAppSyncApi:
  name:  ${self:custom.myAppSyncApi.name}
  authenticationType: AWS_IAM # AMAZON_COGNITO_USER_POOLS
  ...
```
and referenced it (- Ref : myAppSyncApi) in cognito.yml:
### cognito.yml
```
Resources:
  ...               
  CognitoUnauthRole:
    ...
                Resource:
                  Fn::Join:
                    - ""
                    - - "arn:aws:appsync:${self:provider.region}:"
                      - Ref : AWS::AccountId
                      - ":apis/"
                      - Ref : myAppSyncApi
                      - "/types/Query/fields/listEconomicIndicators"
```
Deployment fails because Serverless Framework cannot comprehend the appsync.yml file with myAppSyncApi: at the top. I get:
`Error: appSync property `authenticationType` is missing or invalid…`

I had really hoped this would work because I have successfully achieved very similar when referencing DynamoDB and Cognito resources, etc.
### ATTEMPT 2
I put appsync.yml back to the way it was, and tried referencing the api, by its name, in cognito.yml:
### cognito.yml
```
Resources:
  ...               
  CognitoUnauthRole:
    ...
                Resource:
                  Fn::Join:
                    - ""
                    - - "arn:aws:appsync:${self:provider.region}:"
                      - Ref : AWS::AccountId
                      - ":apis/"
                      - Fn::GetAtt:
                        - ${self:custom.myAppSyncApi.name}
                        - ApiId
                      - "/types/Query/fields/listEconomicIndicators"
```
But, upon deployment, I got the following error:
`Error: The CloudFormation template is invalid: Template error: instance of Fn::GetAtt references undefined resource aws-application-api`
### ATTEMPT 3
Clutching at straws, I tried:
### cognito.yml
```
Resources:
  ...               
  CognitoUnauthRole:
    ...
                Resource:
                  Fn::Join:
                    - ""
                    - - "arn:aws:appsync:${self:provider.region}:"
                      - Ref : AWS::AccountId
                      - ":apis/"
                      - Ref: ${self:custom.myAppSyncApi.name}
                      - "/types/Query/fields/listEconomicIndicators"
```
But I got:
`Error: The CloudFormation template is invalid: Template format error: Unresolved resource dependencies [aws-application-api] in the Resources block of the template`

I really don’t know what I’m missing, but I feel I should be able to do something along the lines of attempt 1, and guess I am missing how I can give the resource a reference name (e.g. myAppSyncApi) within the template. Please can you give me some guidance?

Thanks in advance!

**Comment by bboure** [comment]
@IanAtDazed Sorry for responding so late.
Hope you found a solution, but in case you haven't or others have the same issue, here it is:

Basically, yu need the logical id of your Api Resource.
It is defined [here](https://github.com/sid88in/serverless-appsync-plugin/blob/master/index.js#L864)

In your case it would be `Aws-application-apiGraphQlApiId`

So you should be able to do
````yaml
- Fn::GetAtt:
  - Aws-application-apiGraphQlApiId
  - ApiId
````

Note that I am not sure how Cfn would react to those `-`. I would keep it all CamelCase.

See also [here](https://github.com/sid88in/serverless-appsync-plugin/blob/master/index.js#L16) and [here](https://github.com/sid88in/serverless-appsync-plugin/blob/master/index.js#L848) for more details.

**Comment by ircmgr** [comment]
Since all the  links are broken can someone update them or make a proper example ?- having the same issue

**Comment by bboure** [comment]
@ircmgr Basically, the Logical id of the API resource is:
`GraphQlApiId` if you have only one API
`capitalize(name + GraphQlApiId)` if you have only one API

name is from `custom.appsync.name`

See here: https://github.com/sid88in/serverless-appsync-plugin/blob/master/src/index.js#L982

**Comment by ales-tsvil-clearscale** [comment]
@bboure `Fn::GetAtt` hasn't worked for me.
Trying to refer in serverless.yaml to create SSM parameter with ApiURL of App Sync in it.
```
...
custom:
  appSync:
      name: 'appsync-${self:provider.stage}-api'
      authenticationType: API_KEY
      schema: 'src/appsync/schema.graphql'
      component: '@serverless/aws-app-sync'
      mappingTemplatesLocation: 'src/appsync/mapping-templates'
... 
resources:
 Resources: 
    AppSyncApiURL:
      Type: AWS::SSM::Parameter
      Properties:
        Name: /${self:provider.stage}/data_processing/appsync/api_url
        Type: String
        Value:
          Fn::GetAtt:
            - Appsync-${self:provider.stage}-processing-apiGraphQlApiUrl
            - GraphQLUrl
...
```

I got the following error: 
`  Error: The CloudFormation template is invalid: Template error: instance of Fn::GetAtt references undefined resource Appsync-dev-api
  `
