### ISSUE TITLE
Functions in Pipelines

### ISSUE THREAD

**Issue by andreasonny83** [sid88in/serverless-appsync-plugin#292]
I'm trying to create a Pipeline using a function inside, however, I cannot work around this problem
`Error: The CloudFormation template is invalid: Template error: instance of Fn::GetAtt references undefined resource GraphQlFunctionConfigurationshuffleAvatar`

This is my configuration, please help

```
functions:
  graphql:
    handler: handler.graphqlHandler

custom:
  appSync:
      mappingTemplates:
        - type: Mutation
          field: shuffleAvatar
          request: "shuffle-avatar-request-mapping-template-before.txt"
          response: "shuffle-avatar-response-mapping-template-after.txt"
          kind: PIPELINE
          functions:
            - shuffleAvatar
          functionConfigurations:
            - dataSource: graphqlLambda
              name: 'shuffleAvatar'
              request: "shuffle-avatar-request-mapping-template.txt"
              response: "shuffle-avatar-response-mapping-template.txt"
      dataSources:
      - type: AWS_LAMBDA
        name: graphqlLambda
        description: 'Lambda DataSource'
        config:
          functionName: graphql
```

Thanks

**Comment by andreasonny83** [comment]
Also tried with
```
dataSources:
      - type: AWS_LAMBDA
        name: graphqlLambda
        description: 'Lambda DataSource'
        config:
          lambdaFunctionArn: { Fn::GetAtt: [GraphqlLambdaFunction, Arn] } 
```

`Error: The CloudFormation template is invalid: Template error: instance of Fn::GetAtt references undefined resource GraphQlFunctionConfigurationshuffleAvatar`

**Comment by dobeerman** [comment]
@andreasonny83 have you solve this issue?

**Comment by andreasonny83** [comment]
Hi @dobeerman . Yes, I found a working solution for that.
That was an indentation problem. Moving `functionConfigurations` on the same level of `mappingTemplates` solved the problem

```
functions:
  graphql:
    handler: handler.graphqlHandler

custom:
  appSync:
      mappingTemplates:
        - type: Mutation
          field: shuffleAvatar
          request: "shuffle-avatar-request-mapping-template-before.txt"
          response: "shuffle-avatar-response-mapping-template-after.txt"
          kind: PIPELINE
          functions:
            - shuffleAvatar
      functionConfigurations:
        - dataSource: graphqlLambda
          name: 'shuffleAvatar'
          request: "shuffle-avatar-request-mapping-template.txt"
          response: "shuffle-avatar-response-mapping-template.txt"
      dataSources:
      - type: AWS_LAMBDA
        name: graphqlLambda
        description: 'Lambda DataSource'
        config:
          functionName: graphql
```

I have a working project using that syntax if you need help: https://github.com/Online-Memory/online-memory/blob/master/packages/server/serverless.yml
