### ISSUE TITLE
Multiple API Configuration causing error

### ISSUE THREAD

**Issue by wilderbonsai** [sid88in/serverless-appsync-plugin#297]
Hey there,

I'm trying to implement the multiple api configuration as described by the docs
```If you have multiple APIs and do not want to split this up into another CloudFormation stack, simply change the appSync configuration property from an object into an array of objects:```

e.g
```
custom:
  appSync:
    - name: private-appsync-endpoint
      schema: AppSync/schema.graphql # or something like AppSync/private/schema.graphql
      authenticationType: OPENID_CONNECT
      openIdConnectConfig:
      ...
      serviceRole: AuthenticatedAppSyncServiceRole
      dataSources:
      ...
      mappingTemplatesLocation: ...
      mappingTemplates:
      ...
    - name: public-appsync-endpoint
      schema: AppSync/schema.graphql # or something like AppSync/public/schema.graphql
      authenticationType: NONE # or API_KEY, you get the idea
      serviceRole: PublicAppSyncServiceRole
      dataSources:
      ...
      mappingTemplatesLocation: ...
      mappingTemplates:
      ...
```

However, in all cases that I've tried, I keep running into this error
`Serverless: ERROR: TypeError: Cannot read property 'filter' of undefined`

Any ideas what might be wrong?
It has been working perfectly in a single API configuration

I am using this in conjunction with `serverless-appsync-offline` to develop and test locally.
