### ISSUE TITLE
The CloudFormation template is invalid: [/Outputs/AppSyncLambdaServiceRole] 'null' values are not allowed in templates

### ISSUE THREAD

**Issue by theburningmonk** [sid88in/serverless-appsync-plugin#303]
Here's my `serverless.yml` simplified

```yml
functions:
  createProfile:
    handler: functions/create-profile.handler

custom:
  appSync:
    name: appsync-api
    authenticationType: AMAZON_COGNITO_USER_POOLS
    userPoolConfig:
      awsRegion:  eu-west-1
      defaultAction: ALLOW
      userPoolId: !Ref CognitoUserPool
    mappingTemplates:
      - dataSource: createProfileDataSource
         type: Mutation
         field: createProfile
         request: createProfile-request-mapping-template.txt
         response: createProfile-response-mapping-template.txt
    dataSources:
      - type: AWS_LAMBDA
        name: createProfileDataSource
        description: Create Profile DataSource
        config:
          functionName: createProfile
```

Based on the documentation I had expected the plugin to auto-generate a service role, but when I deploy I don't see the role in the CloudFormation template, and deployment returns the error `The CloudFormation template is invalid: [/Outputs/AppSyncLambdaServiceRole] 'null' values are not allowed in templates`
