### ISSUE TITLE
DataSources as Lambda function has problem

### ISSUE THREAD

**Issue by ntranvinh** [sid88in/serverless-appsync-plugin#305]
Hello,

I am facing an issue that when I create a datasource like this:
```
- type: AWS_LAMBDA
        name: MyFunction
        description: 'MyFunction'
        config:
          lambdaFunctionArn: arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function/${self:custom.servicePrefix}-${opt:stage}-MyFunction
          serviceRoleArn: { Fn::GetAtt: [AppSyncLambdaServiceRole, Arn] }
```

After deployment, the datasource created in Appsync required "region" field which is empty and no lambda function mapped successfully.

Sorry if this is duplicated but I tried to find anything but it is nothing can help.

Please help take a look.

Thank you.
Vinh Nong

**Comment by bboure** [comment]
@ntranvinh The issue might be in the Arn being wrong.

The best, and recommended, way to map your function to a data source is the following: 

```yml
- type: AWS_LAMBDA
    name: MyFunction
    description: "MyFunction"
    config:
      functionName: myFunction
```

where `functionName` (`myFunction`) is the name key of the function on your yaml

```yml
functions:
  myFunction:
    name: MyFunction
    handler: ...
```
