### ISSUE TITLE
Unable to use OpenID defaults - Cannot read property 'issuer' of null

### ISSUE THREAD

**Issue by cyberwombat** [sid88in/serverless-appsync-plugin#308]
I am using 1.2.0. 

This configuration fails with "Cannot read property 'issuer' of null
```
- authenticationType: OPENID_CONNECT
```
This one as well:
```
- authenticationType: OPENID_CONNECT
        openIdConnectConfig:
```
Attempting to enter null or '' values in the field causes deploy errors about invalid values:
```
- authenticationType: OPENID_CONNECT
        openIdConnectConfig:
          issuer: ''
          clientId: ''
          iatTTL: ''
          authTTL: ''
```
Such as `The CloudFormation template is invalid: [/Resources/GraphQlApi/Type/AdditionalAuthenticationProviders/1/OpenIDConnectConfig/Issuer] 'null' values are not allowed in templates`

How does one use OpenID?

**Comment by sid88in** [comment]
This is fixed in v2. A misconfigured OpenID block no longer crashes — the config is validated
up front, so you get a clear message instead:

- `type: OPENID_CONNECT` with no config → "must have required property 'config'"
- config without an issuer → "must have required property 'issuer'"

Correct usage on v2 (note the shape changed from v1 — it's now `authentication` with a generic
`config`):

```yml
appSync:
  authentication:
    type: 'OPENID_CONNECT'
    config:
      issuer: 'https://auth.example.com'
      clientId: '...'   # optional
      iatTTL: 3600      # optional
      authTTL: 3600     # optional
```

Only `issuer` is required. See `doc/authentication.md` → OPENID_CONNECT. Closing as resolved
in v2.
