### ISSUE TITLE
Support Versioned and DeltaSyncConfig

### ISSUE THREAD

**Issue by yyoshiki41** [sid88in/serverless-appsync-plugin#309]
AppSync currently supports versioning on DynamoDB data sources.
https://docs.aws.amazon.com/appsync/latest/devguide/conflict-detection-and-sync.html

I want to configure this options.

Example of CloudFormation template is below.
we need `Versioned` and `DeltaSyncConfig` sections.

```yaml
  DynamoDBPostsTableDatasource:
    Type: AWS::AppSync::DataSource
    Properties:
      Type: AMAZON_DYNAMODB
      Name: posts
      ApiId:
        Fn::GetAtt:
        - DeltaSyncApi
        - ApiId
      ServiceRoleArn: !GetAtt AppSyncTutorialAmazonDynamoDBRole.Arn
      DynamoDBConfig:
        TableName:
          Ref: DynamoDBTableDeltaSyncPostsTable
        AwsRegion:
          Ref: AWS::Region
        UseCallerCredentials: FALSE
        Versioned: TRUE
        DeltaSyncConfig:
          DeltaSyncTableName:
            Ref: DynamoDBTableDeltaSyncDeltaTable
          DeltaSyncTableTTL: 60
          BaseTableTTL: 0
```

thanks.
