### ISSUE TITLE
Cannot deploy HTTP datasource with IAM config attached

### ISSUE THREAD

**Issue by mogusbi-motech** [sid88in/serverless-appsync-plugin#318]
Hi,

I'm trying to add a HTTP data source with authorisation but the AWS is throwing an error every time I try to deploy
 
This is what my configuration looks like

```yml
      dataSources:
        - type: HTTP
          name: ApiEndpoint
          config:
            endpoint: !ImportValue ApiEndpoint
            authorizationConfig:
              authorizationType: AWS_IAM
              awsIamConfig:
                signingRegion: ${self:provider.region}
                signingServiceName: execute-api
```
 and the error I get in return

`The validated string is empty (Service: AWSAppSync; Status Code: 400; Error Code: BadRequestException; Request ID: ###).`

This is the generated Cloudform for that bit

```json
    {
      "Type": "AWS::AppSync::DataSource",
      "Properties": {
        "ApiId": {
          "Fn::GetAtt": [
            "AccountsdevelopGraphQlApi",
            "ApiId"
          ]
        },
        "Name": "ApiEndpoint",
        "Type": "HTTP",
        "HttpConfig": {
          "Endpoint": {
            "Fn::ImportValue": "ApiEndpoint"
          },
          "AuthorizationConfig": {
            "AuthorizationType": "AWS_IAM",
            "AwsIamConfig": {
              "SigningRegion": "eu-west-1",
              "SigningServiceName": "execute-api"
            }
          }
        }
      }
    }
```

Any ideas as to what is going on? Also if I remove the auth config then I am able to deploy the API

**Comment by mogusbi-motech** [comment]
So the problem was that I did not attach IAM policy to the data source, which is why it didn't work. For anyone that runs into the same problem, this is what you'll need to attach to get it working;

```yml
    AppSyncHttpServiceRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: appsync-http-service-role
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - appsync.amazonaws.com
              Action:
                - sts:AssumeRole
        Policies:
          - PolicyName: appsync-http-service-role-policy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - execute-api:Invoke
                  Resource: '*'
```

For added security, make sure you put in your API gateway ARN rather than `*` on the `Resources`.
