### ISSUE TITLE
Misspelled GrqphqlLambdaFunction in cloudformation template

### ISSUE THREAD

**Issue by tempofeng** [sid88in/serverless-appsync-plugin#328]
Trying to deploy my first appsync project to AWS and got the following error:
```
  Error: The CloudFormation template is invalid: Template error: instance of Fn::GetAtt references undefined resource GrqphqlLambdaFunction
      at /Users/tempo/git/strike-usdf-issuer/node_modules/serverless/lib/plugins/aws/deploy/lib/validateTemplate.js:20:13
      at tryCatcher (/Users/tempo/git/strike-usdf-issuer/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/Users/tempo/git/strike-usdf-issuer/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/Users/tempo/git/strike-usdf-issuer/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (/Users/tempo/git/strike-usdf-issuer/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/Users/tempo/git/strike-usdf-issuer/node_modules/bluebird/js/release/promise.js:725:18)
      at _drainQueueStep (/Users/tempo/git/strike-usdf-issuer/node_modules/bluebird/js/release/async.js:93:12)
      at _drainQueue (/Users/tempo/git/strike-usdf-issuer/node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (/Users/tempo/git/strike-usdf-issuer/node_modules/bluebird/js/release/async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (/Users/tempo/git/strike-usdf-issuer/node_modules/bluebird/js/release/async.js:15:14)
      at processImmediate (internal/timers.js:439:21)
      at process.topLevelDomainCallback (domain.js:131:23)
```
There is a misspelled `GrqphqlLambdaFunction` somewhere in the code. (but can't find it in github search)

My `serverless-app-sync-plugin`: 1.3.0
My `serverless.yml`:
```
service: balance-of

plugins:
    - serverless-offline
    - serverless-appsync-offline
    - serverless-appsync-plugin

provider:
    name: aws
    runtime: nodejs12.x

custom:
    appSync:
        authenticationType: API_KEY
        mappingTemplates:
            - dataSource: Lambda
              type: Query
              field: balanceOf
              request: "balanceOf-request.vtl"
              response: "balanceOf-response.vtl"
        dataSources:
            - type: AWS_LAMBDA
              name: Lambda
              config:
                  functionName: grqphql

functions:
    graphql:
        handler: build/graphql.handler
```
