### ISSUE TITLE
Passing Pseudo Parameters to dataSources Resource Causing Policy Failed

### ISSUE THREAD

**Issue by SupervisionT** [sid88in/serverless-appsync-plugin#336]
I'm trying to assignee a role for each dataSources using **iamRoleStatements**
When I pass the region as pseudo parameter **#{AWS::Region}** it failed and got the following error

An error occurred: GraphQlDsusersTableRole - The policy failed legacy parsing (Service: AmazonIdentityManagement; Status Code: 400; Error Code: MalformedPolicyDocument; Request ID: d24b4f63-9de9-410a-9af9-60e0c924fb85).

I have the same context for a lambda function and it works fine!

serverless-appsync-plugin version: 1.3.1

```
plugins:
  - serverless-pseudo-parameters
  - serverless-iam-roles-per-function
  - serverless-appsync-plugin

dataSources:
      - type: AMAZON_DYNAMODB
        name: usersTable
        description: Users Table
        config:
          tableName: {Ref: UsersTable}
          iamRoleStatements:
            - Effect: "Allow"
              Action:
                - "dynamodb:*"
                - "logs:CreateLogGroup"
                - "logs:CreateLogStream"
                - "logs:PutLogEvents"
              Resource:
                - "arn:aws:dynamodb:#{AWS::Region}:*:table/usersTable"
                - "arn:aws:dynamodb:#{AWS::Region}:*:table/usersTable/*"
```
