### ISSUE TITLE
Add Data Sources

### ISSUE THREAD

**Issue by jpstrikesback** [sid88in/serverless-appsync-plugin#34]
The plugin should add data sources as specified in the `custom.appSync.dataSources` key in serverless.yml.

I'm proposing to slightly change the config dataSources structure to:

```yaml
    dataSources:
      - type: AMAZON_DYNAMODB
        name: Users
        description: 'Users table'
        config:
           tableName: 'Users'
           # useCallerCredentials: true # optional, applies to cognito callers
      - type: AMAZON_ELASTICSEARCH
        name: TweetSearch
        description: 'Tweet ES'
        config:
           endpoint: 'Tweets'
      - type: AWS_LAMBDA
        name: UserAvatar
        description: 'User Avatar'
        config:
           lambdaFunctionArn: 'arn:aws:lambda:${REGION}:${ACCOUNT_ID}:function:appsync-lambda-example'
```
