### ISSUE TITLE
Http Endpoint : body null

### ISSUE THREAD

**Issue by leo-regov** [sid88in/serverless-appsync-plugin#342]
Hello,

The request body is null when I am using the HTTP endpoint for the datasource.
I am running the backend service and using appsync offline for sending the request.
I am not sure why it turns null when the request reaches the backend service.

Request (Insomnia)
![image](https://user-images.githubusercontent.com/66946660/88157927-f8f37e80-cc3d-11ea-8812-e3c920844c04.png)
Request body while being sent (Debugging)
![image](https://user-images.githubusercontent.com/66946660/88158072-28a28680-cc3e-11ea-9019-fee045194c5f.png)
Received
![image](https://user-images.githubusercontent.com/66946660/88158187-4d96f980-cc3e-11ea-8f98-3e614547c512.png)

Serverless.yml
```
service:
  name: testAppsync
provider:
  name: aws
plugins:
  - serverless-appsync-plugin
  - serverless-appsync-offline
  - serverless-offline
  - serverless-scriptable-plugin
functions:
  testAppLambda:
    handler: ./build/index.handler
    events:
      - http:
          path: graphql
          method: post
custom:
  appSync:
    name: testAppsync
    authenticationType: API_KEY
    apiKeys:
      - 'testLocalKey'
    mappingTemplates:
      - dataSource: LambdaSource
        type: Mutation
        field: userLogin
        request: 'userLogin.request.vtl'
        response: 'userLogin.response.vtl'
    dataSources:
      - type: HTTP
        name: LambdaSource
        description: "Lambda DataSource"
        config:
          endpoint: "http://localhost:9000/"
  appsync-offline:
    schema: schema.graphql
    port: 62222
    dynamodb:
      endpoint: "http://localhost:8000"
      region: localhost
```
 VTL
```
{
  "version" : "2018-05-29",
  "operation": "Invoke",
  "method": "POST",
  "resourcePath": "/",
  "payload": {
      "TypeName": "Mutation",
      "FieldName": "login",
      "Header": "$utils.toJson($context.request)",
      "Arguments": "$utils.toJson($context.arguments)"
  }
}
```
I am using the vtl in my Appsync console with Lambda resolver and it is working, only added the double quotes for this serverless implementation.
Backend is running with AWS SAM CLI. (For development and testing)

Thanks for any help.
