### ISSUE TITLE
How can I split the appsync into multiple stack?

### ISSUE THREAD

**Issue by zhaoyi0113** [sid88in/serverless-appsync-plugin#344]
First of all, thanks a lot for releasing this awesome plugin. I have a question about how to split the appsync into multiple stack?

I have a project to deploy a `appsync` API using this plugin. And it only deploys the Appsync instance and logging and authentication. It doesn't include any schema, resolvers etc. 

And I have a few other projects each of which is to deploy schema, resolvers to the Appsync deployed by the previous project. In these projects, they need to import the appsync infra in order to attach these resolvers.

That means there will be multiple cloudformation stacks created and using cross stack reference among them. I wonder how I can make this by using this plugin.

**Comment by bboure** [comment]
Hi @zhaoyi0113 are you doing this intentionally in order to split concerns or is it due to the CloudFormation restriction on stack size?

For the Cfn restrictions, there is [this plugin](https://github.com/dougmoscrop/serverless-plugin-split-stacks)

Otherwise, you should be good by referencing the ARN's as you suggested.
You can probably do that using [Output references](https://www.serverless.com/framework/docs/providers/aws/guide/variables#reference-cloudformation-outputs) from serverless.

By default, this plugin outputs:
- The Api url
- Api Id
- Api Key

See [here](https://github.com/sid88in/serverless-appsync-plugin/blob/master/src/index.js#L313-L314)

But you can manually output any resource.

**Comment by zhaoyi0113** [comment]
I am doing it intentionally not because of 200 resources limitation. I'd like to control each stack resources. I know it exports these values but how can I use these values in this plugin? The only way I can think of is to create `resolvers`, `datasource` via Cloudformation. Is there a way to attach `resolvers` to an existing appsync via this plugin?

**Comment by bboure** [comment]
@zhaoyi0113 I think I know what you mean now.

The only thing you can really separate are the data sources (Lambda functions, Dynamodb tables, etc)
Then, you can reference them in the datasource config:

```yml
     - type: AMAZON_DYNAMODB
        name: myDynamo
        config:
          tableName:
            'Fn::ImportValue': MyDynamoDbName
    - type: AWS_LAMBDA
        name: myLambda
        config:
          lambdaFunctionArn:
            'Fn::ImportValue': MyFunctionArn
```

What you cannot do is separate the mapping template and datasource definitions from the AppSync definition. 

In other words, everything under `custom.appSync` MUST go into the same stack.

**Comment by zhaoyi0113** [comment]
right, that's what my concern really is. If I want to separate the definition, I will have to use cloudformation `Resources`, like:

```
resources:
    Resources:
        Resources:
           myDataSource:
          Type: AWS::AppSync::DataSource
          Properties:
             Name: myDataSource
            ApiId:
                Fn::ImportValue: !Sub '${appsyncStackName}-graphQlApiId'
           Type: AWS_LAMBDA
        ...
```
and in above settings,  the `ApiId` is imported from the appsync stack.
