### ISSUE TITLE
How can I export appsync url and id?

### ISSUE THREAD

**Issue by zhaoyi0113** [sid88in/serverless-appsync-plugin#345]
I have blow configure to export `GraphQlApiId` on the cloudformation stack but I can't see the exported name on cloudformation stack console. 
What is the correct way to export the values?

```
resources:
  Outputs:
    GraphQlApiId:
      Value: !GetAtt GraphQlApi. GraphQlApiId
      Export:
        Name: !Join ['', ['${self:provider.stackName}', '-graphQlApiId']]
```

**Comment by bboure** [comment]
@zhaoyi0113 the id and urls are exported by default by the plugin [here](https://github.com/sid88in/serverless-appsync-plugin/blob/master/src/index.js#L985-L997) under the names `GraphQlApiUrl` and `GraphQlApiId``

From another stack, you should be able to access them through: 
```
'Fn::ImportValue': GraphQlApiUrl
```

**Comment by zhaoyi0113** [comment]
I see it exports these values but I can't set the `Export Name`. I can only see `key` and `value`.

**Comment by rehrumesh** [comment]
Having the same trouble as @zhaoyi0113

**Comment by bboure** [comment]
There is a PR open for that #392

I'll merge it  soon

**Comment by sid88in** [comment]
Heads up that the "exported by default" behavior was a v1 thing — on v2 the plugin no longer
emits Outputs automatically (PR #392 was for the v1 line and is superseded). You now control
exports yourself, which is cleaner.

Two fixes for your snippet: the GetAtt attribute is `ApiId`, not `GraphQlApiId`, and the
easiest path is the plugin's variable sources:

```yml
resources:
  Outputs:
    GraphQlApiId:
      Value: ${appsync:id}    # GetAtt [GraphQlApi, ApiId]
      Export:
        Name: ${self:provider.stackName}-graphQlApiId
    GraphQlApiUrl:
      Value: ${appsync:url}   # GetAtt [GraphQlApi, GraphQLUrl]
      Export:
        Name: ${self:provider.stackName}-graphQlApiUrl
```

Then `Fn::ImportValue` from the other stack. Also available: `${appsync:arn}` and
`${appsync:apiKey.<name>}`.

Closing as a duplicate of #390 (where I'll add proper docs for this). Thanks @zhaoyi0113
@rehrumesh.
