### ISSUE TITLE
How can I add a DeletionPolicy?

### ISSUE THREAD

**Issue by jimpala** [sid88in/serverless-appsync-plugin#389]
Hiya! Ordinarily in a CF YAML template I'd add a `DeletionPolicy` to a resource like so:
```yaml
myAppSyncApi:
  Type: AWS::AppSync::GraphQLApi
  Properties:
    # ...
  DeletionPolicy: Retain
```

But looking at the code that generates the top-level `AWS::AppSync::GraphQLApi` resource I'm looking to add a `DeletionPolicy` for, it looks like there is no way to add a key on the same level as `Type` and `Properties`, which is where `DeletionPolicy` should live:

https://github.com/sid88in/serverless-appsync-plugin/blob/a083af5a01349c87592a73a3687f0a3eb9452f8e/src/index.js#L389-L423

Please let me know if I'm missing something 😄 and thanks for the great library!

**Comment by sid88in** [comment]
You're right that there's no per-resource `DeletionPolicy` config — but you don't need one.
Use Serverless's native `resources.extensions`, keyed on the resource's logical id. For the
API that's `GraphQlApi`:

```yml
resources:
  extensions:
    GraphQlApi:
      DeletionPolicy: Retain
      UpdateReplacePolicy: Retain
```

I verified this lands on the synthesized `AWS::AppSync::GraphQLApi` (the plugin adds its
resources early enough that core's `extensions` merge picks them up). The same works for any
logical id the plugin generates (`GraphQlSchema`, `GraphQlApiLogGroup`, `GraphQlDs<Name>`,
etc.).

For the custom domain specifically there's also a dedicated `domain.retain: true` option
(see `doc/custom-domain.md`).

This isn't documented yet — I'll add a short section on it. Closing as answered.
