### ISSUE TITLE
Adding an option for Output Exports

### ISSUE THREAD

**Issue by dillonbrowne** [sid88in/serverless-appsync-plugin#390]
Feature Request:  Allow cross-stack reference to be able to use `Fn::ImportValue` in other CF stacks.

**Comment by dillonbrowne** [comment]
handled via `--conceal`

**Comment by sid88in** [comment]
I'm going to close this as already achievable rather than build auto-exports into the plugin.
The plugin exposes the API values as variable sources, and you can export them the standard
Serverless way:

```yml
resources:
  Outputs:
    AppSyncApiUrl:
      Value: ${appsync:url}
      Export:
        Name: ${self:service}-${sls:stage}-AppSyncUrl
    AppSyncApiId:
      Value: ${appsync:id}
      Export:
        Name: ${self:service}-${sls:stage}-AppSyncId
    # also available: ${appsync:arn}, ${appsync:apiKey.<keyName>}
```

Other stacks then consume them with `Fn::ImportValue`.

I'd rather not auto-emit exports: export names are globally unique per region/account, and an
exported value can't be changed (or its resource deleted) while another stack imports it — so
auto-exporting risks collisions and locking resources. Opting in per the above keeps you in
control of exactly what's exported and under what name.

Closing as resolved via existing functionality — reopen if there's a case the variable
sources don't cover.
