### ISSUE TITLE
service role to data source mapping

### ISSUE THREAD

**Issue by sid88in** [sid88in/serverless-appsync-plugin#40]
const serviceRoleElastic = `arn:aws:iam::${accountId}:role/${roleNameElastic}`; // Service IAM Role for appsync to access data sources
const serviceRoleDynamo = `arn:aws:iam::${accountId}:role/${roleNameDynamo}`; // Service IAM Role for appsync to access data sources

you may have 2 or more service roles and each data source is associated with 1 role: 

    const datasourceParams = [
      {
        apiId: appId /* required */,
        name: 'elastic' /* required */,
        type: 'AMAZON_ELASTICSEARCH' /* required */,
        description: 'my first data source',
        elasticsearchConfig: {
          awsRegion: awsRegion /* required */,
          endpoint: esEndpoint /* required */,
        },
        serviceRoleArn: serviceRoleElastic,
      },
      {
        apiId: appId /* required */,
        name: 'Users' /* required */,
        type: 'AMAZON_DYNAMODB' /* required */,
        description: 'Store user info',
        dynamodbConfig: {
          awsRegion: awsRegion /* required */,
          tableName: 'ESUsers' /* required */,
        },
        serviceRoleArn: serviceRoleDynamo,
      },
    ];

taking example below from readme of appsync plugin:

    serviceRole: # required - example: "arn:aws:iam::${self:custom.accountId}:role/EXAMPLE-Role"
    dataSources:
      - type: AMAZON_DYNAMODB
        name: Users
        description: 'Users table'
        config:
           tableName: 'Users'

**Comment by jpstrikesback** [comment]
Now that the serviceRoleArn is obtained from the Data Sources I just need to update the readme (on my phone or I’d PR it now) like so:


```yaml
    ...
    serviceRole: "AppSyncServiceRole"
    dataSources:
      - type: AMAZON_DYNAMODB
        name: Users
        description: 'Users table'
        config:
          tableName: 'Users'
          serviceRoleArn: "arn:aws:iam::${self:custom.accountId}:role/Dynamo-${self:custom.appSync.serviceRole}"
      - type: AMAZON_DYNAMODB
        name: Tweets
        description: 'Tweets table'
        config:
          tableName: 'Tweets'
          serviceRoleArn: "arn:aws:iam::${self:custom.accountId}:role/Dynamo-${self:custom.appSync.serviceRole}"
      - type: AMAZON_ELASTICSEARCH
        name: ElasticSearch
        description: 'ElasticSearch'
        config:
          endpoint: # required # "https://{DOMAIN}.{REGION}.es.amazonaws.com"
          serviceRoleArn: "arn:aws:iam::${self:custom.accountId}:role/ElasticSearch-${self:custom.appSync.serviceRole}"
      - type: AWS_LAMBDA
        name: Lambda_MeInfo
        description: 'Lambda DataSource'
        config:
          lambdaFunctionArn: "arn:aws:lambda:us-east-1:${self:custom.accountId}:function:appsync-example-dev-graphql"
          serviceRoleArn: "arn:aws:iam::${self:custom.accountId}:role/Lambda-${self:custom.appSync.serviceRole}"

```

And also show how to use that in the resources section for the initial deploy.
