### ISSUE TITLE
Error: Unknown type "Query"

### ISSUE THREAD

**Issue by alanionita** [sid88in/serverless-appsync-plugin#415]
Just following the example and getting the following error

```bash
AppSync Plugin: Error: Unknown type "Query".
```

The serverless.yml stack seems to be fine

```yaml
    mappingTemplates:
      - dataSource: testGraphqlApiTableDS
        type: Query
        field: getUser
        request: "getUser-req.vtl"
        response: "common-res.vtl"
      - dataSource: testGraphqlApiTableDS
        type: Mutation
        field: saveUser
        request: "saveUser-req.vtl"
        response: "common-res.vtl"
      - dataSource: testGraphqlApiTableDS
        type: Mutation
        field: deleteUser
        request: "deleteUser-req.vtl"
        response: "common-res.vtl"
```
