### ISSUE TITLE
Get the name of the source dynamically into the VLT

### ISSUE THREAD

**Issue by mariano-calandra-xp** [sid88in/serverless-appsync-plugin#421]
Hi, I'm using this plugin to configure a mutation. 
This is the main configuration:
```
mappingTemplates:
  - type: Mutation
    field: addPost
    dataSource: postsTable

...

dataSources:
  - type: AMAZON_DYNAMODB
    name: postsTable
    config:
      tableName: !Ref PostsTable
```

and this is the VLT

```
#set($posts = [])
#foreach($item in ${context.arguments.posts})
    ...
#end

{
    "version" : "2018-05-29",
    "operation" : "BatchPutItem",
    "tables" : {
        "post-table": $utils.toJson($posts)
    }
}
```

In the VLT I'm forced to use post-table, but I would like to have this as a parameter that should be equal to the `dataSource.config.tableName`. 

Is there a way to do this?

**Comment by bboure** [comment]
@mariano-calandra-xp you can use substitutions for that:

```vtl
{
    "version" : "2018-05-29",
    "operation" : "BatchPutItem",
    "tables" : {
        "${tableName}": $utils.toJson($posts)
    }
}
```

```yml
mappingTemplates:
  - type: Mutation
    field: addPost
    dataSource: postsTable
    substitutions:
      - tableName: !Ref PostsTable

```

or, globally

```yaml
appsync:
  substitutions:
    - tableName: !Ref PostsTable
```

**Comment by marianoc84** [comment]
Just a quick extra @bboure, the correct way is without the hyphen.

```
mappingTemplates:
  - type: Mutation
    field: addPost
    dataSource: postsTable
    substitutions:
      tableName: !Ref PostsTable
```
