### ISSUE TITLE
AWS_LAMBDA Custom Authorizer support

### ISSUE THREAD

**Issue by sweepy84** [sid88in/serverless-appsync-plugin#425]
AWS have finally released custom authorizer support for AppSync (much like API Gateway) using Lambda as reported > https://aws.amazon.com/about-aws/whats-new/2021/07/aws-appsync-supports-custom-authorization-with-aws-lambda-graphsql-apis/

There is now no need to use Pipeline resolvers to implement custom authorisation. The AWS_LAMBDA option can be set as the default authorizer for all types.

Would be great if the plugin supports this now native feature.

**Comment by bboure** [comment]
Thanks, @sweepy84 

This is definitely something I'd like to see in the plugin
I'll try to get something done in the following days.

**Comment by harinair** [comment]
+1

**Comment by sid88in** [comment]
This shipped in v2. `AWS_LAMBDA` is supported both as the default authorizer and as an
additional auth provider, so you can use it as the default for all types as AWS intended.

Config lives under `authentication` (and `additionalAuthentications`):

```yml
appSync:
  authentication:
    type: 'AWS_LAMBDA'
    config:
      authorizerResultTtlInSeconds: 300
      identityValidationExpression: 'some-regex'
      function:
        handler: 'auth.handler'
```

The plugin emits the `LambdaAuthorizerConfig` on the API and adds the
`lambda:InvokeFunction` permission for AppSync automatically. Docs:
`doc/authentication.md` → "Lambda".

Thanks @sweepy84 for flagging it when AWS first released this. Closing as implemented.
