### ISSUE TITLE
How to use substitutions per resolver? 

### ISSUE THREAD

**Issue by sc0ttdav3y** [sid88in/serverless-appsync-plugin#434]
Hi,

I see there's a merged feature [to support substitutions per resolver](https://github.com/sid88in/serverless-appsync-plugin/pull/252) but I can't see any documentation on how to use it. 

Can I get some hints on where to put this in config if I want it per resolver?

It's not in the docs.

Thanks!

**Comment by bboure** [comment]
Hi @sc0ttdav3y 

Thanks for pointing out the missing doc.
You can use per-resolver substitution by adding a `substitutions` key under your mapping templates:

```yml
  appsync:
    mappingTemplates:
    - type: Query
      dataSource: myTable
      field: myQuery
      substitutions:
        myVar: 'myValue'
```

I'll update the doc.
