### ISSUE TITLE
Substitutions not working

### ISSUE THREAD

**Issue by AbhishekDesai99** [sid88in/serverless-appsync-plugin#450]
This is my runtime configurations, 
Node - 12.18.3
Serverless - 2.66.2

Tested it with the latest plugin version - 1.12.0, but it is not replacing variable values on the VTL templates
Here is my code,

serverless.yml 
````
service: temp
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: 'us-west-2'

custom:
  appSync:
    - ${file(appsync.yml)}
    

plugins:
  - serverless-appsync-plugin

resources:
  Resources:
    AppSyncLoggingServiceRole:
      Type: "AWS::IAM::Role"
      Properties:
        RoleName: "appsync-testing"
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Principal:
                Service:
                  - "appsync.amazonaws.com"
              Action:
                - "sts:AssumeRole"
        Policies:
          - PolicyName: "appsync-testing"
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: "Allow"
                  Action: ["logs:CreateLogGroup", "logs:CreateLogStream", "logs:PutLogEvents"]
                  Resource: "*"
````

appsync.yml
````
name: appsync-testing
schema: schema.api.graphql
authenticationType: API_KEY
apiKeys:
  - name: 'GuestKey'
    description: 'API key protection for open appsync endpoints'
logConfig:
  loggingRoleArn: { Fn::GetAtt: [AppSyncLoggingServiceRole, Arn] }
  level: ALL
  excludeVerboseContent: false
mappingTemplatesLocation: mapping-templates
mappingTemplates:
  - type: Mutation
    field: testing
    dataSource: none
  - type: Query
    field: testing
    dataSource: none
    substitutions:
      myVar2: "Hello world 2"
substitutions:
  myVar: "Hello world"
dataSources:
  - type: NONE
    name: none
````

I tried with both the approaches, a resolver level substitution, and a global level, but none of them worked for me. Can anyone help me to find out what is going wrong?
