### ISSUE TITLE
Lambda Resolver Example

### ISSUE THREAD

**Issue by arunwij** [sid88in/serverless-appsync-plugin#455]
Hi, 

I am trying to use a Lambda Resolver for a query, but the code provided in the example configuration is not clear. Could you please explain what's happening here with **GraphqlLambdaFunction** ? 

```YAML
- type: AWS_LAMBDA
     name: Lambda_MeInfo
     description: 'Lambda DataSource'
     config: 
          functionName: graphql
          lambdaFunctionArn: { Fn::GetAtt: [GraphqlLambdaFunction, Arn] } #
          serviceRoleArn: { Fn::GetAtt: [AppSyncLambdaServiceRole, Arn] }
```
          
I assume **GraphqlLambdaFunction** is a logical ID. But I cannot find any place which defines this value in serverless.yml.  Could you please give an example for this?

**Comment by bboure** [comment]
Hi,

Your indentation seems wrong.

Also, the simplest way to setup a lambda data source is using the `funcitonName` attribute.
`functionName` and `lambdaFunctionArn` are mutually exclusives and just two different way to configure it

`functionName` is the name (key) of your function in the `functions` section of your `serverless.yml` file.

The Arn will be resolved automatically by the plugin.
Unless special use cases, you should not need to setup `serviceRoleArn` either. The plugin will generate one for you. 
If you need custom statements in the IAM role, you can also use `config.statements`

```yaml
# serverless.yml
functions:
  graphql:
    handler: index.handler
```

```yaml
# appsync config
  - type: AWS_LAMBDA
     name: Lambda_MeInfo
     description: 'Lambda DataSource'
     config: 
          functionName: graphql
```
