### ISSUE TITLE
Feature request: Inline Lambda data sources within mappingTemplates

### ISSUE THREAD

**Issue by paulswail** [sid88in/serverless-appsync-plugin#482]
Hooking up Lambda functions as resolvers currently feels quite verbose and disconnected: first define the function in standard `functions` section, then add an item to the plugin's `mappingTemplates` section and then also define a separate data source. If you're using single-responsibility Lambda functions, the configuration file really grows.

Ideally it would be great if an `appsync` event could be defined in the standard `functions.functionName.events` array in serverless.yml so that the function and the resolver that triggers it are configured in the same place. However, I guess this may not be easy to hook into for a plugin, so instead would it even be possible to inline the data source within the mappingTemplates section rather than having to define it separately? I'm thinking of something like this:

```yml
mappingTemplates:
  - type: Mutation
     field: updateProfile
     dataSource:
       type: AWS_LAMBDA
       functionName: updateProfile
```

**Comment by bboure** [comment]
Keep an eye on v2 :)

https://github.com/sid88in/serverless-appsync-plugin/blob/v2/doc/resolvers.md#inline-datasources

**Comment by paulswail** [comment]
Beautiful! 😃 Thank you @bboure 
I know you mightn't be able to say, but do you have a rough idea of when v2 will be ready?

**Comment by bboure** [comment]
I'm expecting to launch an alpha soon (in a few weeks at most).

I'm a bit busy with client work right now :)

**Comment by sid88in** [comment]
This shipped in v2. A resolver's dataSource can now be inlined directly instead of referencing a separately-defined one — and you can even inline the Lambda function definition under it, so the function, data source, and resolver all live in one place:

```
resolvers:
  Mutation.updateProfile:
    kind: UNIT
    dataSource:
      type: 'AWS_LAMBDA'
      config:
        function:
          handler: 'functions/updateProfile.handler'
```

Pipeline functions can be inlined the same way. See Inline DataSources. Closing as implemented — thanks for the suggestion @paulswail, and glad v2 landed it. 🙂
