### ISSUE TITLE
Mapping Template Location Update

### ISSUE THREAD

**Issue by DChan0319** [sid88in/serverless-appsync-plugin#522]
Want to be able to define different locations of where mapping templates can live. Right now, current implementation only allows for single directory location. I want to be able to pull mapping templates from multiple child directories that have different paths.

**Comment by sid88in** [comment]
This is handled by the v2 design. v2 dropped the single mappingTemplatesLocation option — instead, every resolver and pipeline function points to its own request/response template path (relative to serverless.yml), so your templates can live in as many different directories as you want. For example:
yaml

```
resolvers:
  Query.user:
    dataSource: users
    request: src/users/get.request.vtl
    response: src/users/get.response.vtl
  Mutation.createOrder:
    dataSource: orders
    request: src/orders/templates/create.request.vtl
    response: shared/vtl/passthrough.response.vtl
```

Closing as resolved by v2 — see the resolvers docs for the full config. Thanks @DChan0319 !
