### ISSUE TITLE
userPoolId cannot be resolved for playground

### ISSUE THREAD

**Issue by aserrallerios** [sid88in/serverless-appsync-plugin#523]
Hello, my `userPoolId` is dynamic, so when I run `graphql-playground` I got an error:

```yaml
    userPoolConfig:
      awsRegion: ${self:provider.region}
      defaultAction: ALLOW
      userPoolId:
        Ref: cognitoUserPoolUsers
```

```
Error: userPoolConfig.userPoolId: Ref "cognitoUserPoolUsers not found
```

Is there any way the plugin could solve it?

If not, should `userPoolId` be a CLI parameter, just like `--clientId`? Right now my workaround is to hardcode the Id.
