### ISSUE TITLE
Invalid Endpoint Configuration

### ISSUE THREAD

**Issue by celestialorb** [sid88in/serverless-appsync-plugin#56]
I'm encountering an "Invalid endpoint configuration" error when I attempt to deploy a new AppSync API with an ElasticSearch domain as my data source.

The ES domain is on the same AWS account, has been created, and is ready for use.  The `custom` part of my serverless.yml file is below, and the `endpoint` parameter was copy/pasted into it.
```yaml
custom:
  accountId: [REDACTED]
  appSync:
    name: [REDACTED]
    authenticationType: API_KEY
    serviceRole: "AppSyncServiceRole"
    region: [REDACTED]
    schema: schema.graphql
    dataSources:
      - type: AMAZON_ELASTICSEARCH
        name: [REDACTED]
        config:
          endpoint: https://vpc-[REDACTED]-[REDACTED].[REDACTED].es.amazonaws.com
          serviceRoleArn: "???"
```

I have tried several different serviceRoleArns but nothing seems to make a difference.

What am I doing wrong?  I'm pulling my hair out here.
