### ISSUE TITLE
Adding an AWS_LAMBDA authentication method results in circular dependency

### ISSUE THREAD

**Issue by chrisharrison** [sid88in/serverless-appsync-plugin#567]
If I add this:

```
additionalAuthenticationProviders:
      - authenticationType: API_KEY
      - authenticationType: AWS_IAM
      - authenticationType: AWS_LAMBDA
        lambdaAuthorizerConfig:
          functionName: customAuth
          authorizerResultTtlInSeconds: 300
```

and:

```
functions:
  customAuth:
    handler: build/handlers/customAuth.handle
```

to an existing API. I get the following error:
`The CloudFormation template is invalid: Circular dependency between resources:`

More specifically:

```
The CloudFormation template is invalid: Circular dependency between resources: [GraphQlResolverMutationcreateHeartBeat, CreateGateClosuresLambdaFunction, GraphQlSchema, GraphQlDsGetGateClosuresLambda, BackfillEpexDataLambdaFunction, BackfillTradeStatusesLambdaFunction, CreateGateClosuresSnsSubscriptionDomainservicedevschedulegate, GraphQlResolverMutationcreateZapiResponse, GraphQlDsLocal, TestDataPrivateTradesLambdaFunction, GraphQlApiKeyDefault, GraphQlResolverQuerygetPrivateTrades, GraphQlResolverMutationcreateInternalPowerTransfer, GraphQlResolverQuerygetZapiSubmissions, GraphQlApiLogGroup, GraphQlResolverMutationcreateInternalTradeAllocation, GraphQlApiLambdaAuthorizerPermission, GraphQlDsCreateInternalPowerTransferLambda, GraphQlResolverMutationcreateContract, GraphQlResolverMutationcreateCurrentGateClosures, GraphQlDsCreateZapiResponseLambda, GetGateClosuresLambdaFunction, GraphQlResolverMutationcreateNopChangeset, CreateGateClosuresLambdaPermissionDomainservicedevschedulegateSNS, RunMigrationsLambdaFunction, CustomAuthLambdaFunction, GraphQlApi, GraphQlResolverQuerygetCurrentGateClosures, GraphQlResolverQuerygetTradingAllowedState, GraphQlDsCreateInternalTradeAllocationLambda, GraphQlResolverQuerygetWapsForProducts, GraphQlDsRDS, GraphQlResolverQuerygetNop, GraphQlResolverMutationcreateNotification]
```

If I remove the additional authentication provider, the error goes away.

Any idea what's causing that? Because I can't see the connection between adding a new function and setting it up as an appsync authoriser and a circular dependency?

I'm using 1.4.0
