### ISSUE TITLE
Lambda resolver documentation broken

### ISSUE THREAD

**Issue by thordickinson** [sid88in/serverless-appsync-plugin#581]
Hey folks, I think that there is a small error in the documentation. The sample shows this, as the way to define a lambda resolver:

```yaml
appSync:
  resolvers:
    Query.user:
      dataSource:
        type: 'AWS_LAMBDA'
        config:
          function:
            timeout: 30
            handler: 'functions/getUser.handler'
```

But that sample is missing the `functions` property, which it makes impossible to create a lambda resolver, this would be the fix.

```yaml
appSync:
  resolvers:
    Query.user:
      functions:  # <- Here
        - dataSource:
            type: 'AWS_LAMBDA'
            config:
              function:
                timeout: 30
                handler: 'functions/getUser.handler'
```

Hope this helps the entire community
