### ISSUE TITLE
Docs not up to date

### ISSUE THREAD

**Issue by mstoyanovv** [sid88in/serverless-appsync-plugin#588]
The documentation [here](https://www.serverless.com/plugins/serverless-appsync-plugin) is about version 1 of this plugin which is not stated and leads to erros because 'appSync' is no longer under 'custom' in the yaml file. 'npm install serverless-appsync-plugin' would install v2 therefore the whole page is irrelevant. 

The 'up to date' examples in the repo here like the 'quick start' one: 
```
service: my-app

plugins:
  - serverless-appsync-plugin

provider:
  name: aws

appSync:
  name: my-api

  authentication:
    type: API_KEY

  apiKeys:
    - name: myKey
      expiresAfter: 1M

  dataSources:
    my-table:
      type: AMAZON_DYNAMODB
      description: 'My table'
      config:
        tableName: my-table

  resolvers:
    Query.user:
      dataSource: my-table
```

is failing with  "Cannot read properties of undefined (reading 'map')". Looks like the plugin is searching for functions property in a resolver.
