### ISSUE TITLE
AppSync Api not found in stack. Did you forget to deploy?

### ISSUE THREAD

**Issue by owain68** [sid88in/serverless-appsync-plugin#594]
I am getting the error `AppSync Api not found in stack. Did you forget to deploy?`.

I am trying to migrate from V1 of the plugin using the migration [guide](https://github.com/sid88in/serverless-appsync-plugin/blob/master/doc/upgrading-from-v1.md).  

All the resources appear to deploy for a short period of time before a ROLLBACK is issued.  And then they disappear.  I suspect that the Rollback is initiated by the serverless framework itself since the appsync plugin throws this error.

 ```
async getApiId() {
    this.loadConfig();

    if (!this.naming) {
      throw new this.serverless.classes.Error(
        'Could not find the naming service. This should not happen.',
      );
    }

    const logicalIdGraphQLApi = this.naming.getApiLogicalId();

    const { StackResources } = await this.provider.request<
      DescribeStackResourcesInput,
      DescribeStackResourcesOutput
    >('CloudFormation', 'describeStackResources', {
      StackName: this.provider.naming.getStackName(),
      LogicalResourceId: logicalIdGraphQLApi,
    });

    const apiId = last(StackResources?.[0]?.PhysicalResourceId?.split('/'));

    if (!apiId) {
      throw new this.serverless.classes.Error(
        'AppSync Api not found in stack. Did you forget to deploy?',
      );
    }

    return apiId;
  }
```
  
So `apiId` is not found for some reason which throws an exception.  

I am probably missing something in my `serverless.yml` or do I need to explicitly Output some CloudFormation values to fix this.  

Here is the header of my serverless yml file.

```
appSync:
  name: "${self:service}-${self:provider.stage}"
  authentication:
    type: AMAZON_COGNITO_USER_POOLS
    config:
      awsRegion: ${self:provider.region}
      defaultAction: ALLOW
      userPoolId:
        Fn::ImportValue: ${self:custom.resources.PROJECT_PREFIX}-UserPoolId
  additionalAuthentications:
    - type: API_KEY
  apiKeys:
    - name: Default-${self:provider.stage}
      description: Default-${self:provider.stage} generated by Serverless deployment
      expiresAfter: 1y
      apiKeyId: ${self:custom.resources.APPSYNC_API_KEY}
....

```

It would be very helpful if there is a working example available to compare with. 

Thanks in advance.

O.,

**Comment by owain68** [comment]
I have managed to run this through the debugger and the following screenshot shows that [describeStackResources](https://github.com/sid88in/serverless-appsync-plugin/blob/master/src/index.ts#L358) returns an empty array.

I am using `serverless-plugin-split-stacks` so might this be the call pointing to the wrong Stack?

<img width="1012" alt="screenshot_324" src="https://user-images.githubusercontent.com/191453/232296902-49a8ffe0-bf47-40db-8d24-8ec7be2c41bd.png">

`aws cloudformation describe-stack-resources --stack-name my-stack-root-name` returns an array of 100 [the max for this call](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/cloudformation/describe-stack-resources.html#description) so I am not sure why the call is not returning anything.  And yes I am in the correct AWS account!

**Comment by bboure** [comment]
Hi,

Thanks for reporting this and debugging

The split stack plugin is likely the problem here. 
your API resource is probably in a substack, which causes this issue. 

I see two options to fix this:
1. Maybe we can first find in which stack the main API resource is located, then described that stack to extract the data (not sure how to do that yet)
2. If we can't easily detect which stack it is in, we're going to have to describe all stacks until we find the right one.

**Comment by owain68** [comment]
@bboure I have tweaked some of the settings on `serverless.yml` for some of the `serverless-plugin-split-stacks` to 

```
  splitStacks:
    perFunction: false
    perType: false
    perGroupFunction: true
    nestedStackCount: 20
    stackConcurrency: 5 # Controls if enabled and how much stacks are deployed in parallel. Disabled if absent.
    resourceConcurrency: 10 # Controls how much resources are deployed in parallel. Disabled if absent.
```
and there still remains a `LogicalResourceId` of `GraphQlNestedStack` so it looks like this remains constant.  I have had a look at the source of [serverless-plugin-split-stacks](https://github.com/dougmoscrop/serverless-plugin-split-stacks) but I can't work out how this gets set. @dougmoscrop.
