### ISSUE TITLE
accountId in serverless.yml can be any integer

### ISSUE THREAD

**Issue by thenengah** [sid88in/serverless-appsync-plugin#60]
I noticed accountId cannot be missing but as long as it present it can be any number and the deploy goes through successfully. This is a bit confusing because serverless uses the aws profile credentials to figure out which account to deploy to and this accountId in this plugin has no affect. Am I missing something here?

**Comment by sid88in** [comment]
@thenengah good catch. You would need correct account id to configure your data sources. For instance: 
```
      - type: AMAZON_DYNAMODB
        name: Users
        description: 'Users table'
        config:
          tableName: 'Users'
          serviceRoleArn: "arn:aws:iam::${self:custom.accountId}:role/Dynamo-${self:custom.appSync.serviceRole}"
```
So when your deployment goes through your datasource conffiguration might be incorrect and ideally you would recieve IAM issue when making a call to backend. 

But having said that if you somehow don't require the pass accountId in your data source configuration then passing accountId in the root might be unnecessary. 

If you have any thoughts on how to improve this we can look into it :) 

thanks
Sid
