### ISSUE TITLE
not able to use existing logging role

### ISSUE THREAD

**Issue by droger88** [sid88in/serverless-appsync-plugin#646]
we would like to use an existing role for logging configuration because our permission setup, but when the attribute is set, it is still trying to create a new role
appsync configuration
```
appSync:
  name: demo-post-api
  logging:
    level: ALL
    retentionInDays: 14
    enabled: true
    roleArn: "arn:aws:iam::12345:role/appsync-datasource"
....
```
here is the output 
```
✖ Stack test-api failed to deploy (46s)
Environment: darwin, node 18.12.1, framework 3.39.0, plugin 7.2.3, SDK 4.5.1
Credentials: Local, environment variables
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
CREATE_FAILED: GraphQlApiLogGroupRole (AWS::IAM::Role)
Resource handler returned message: "Encountered a permissions error performing a tagging operation,
```
