### ISSUE TITLE
Create AWS Cognito User Pool using this plugin

### ISSUE THREAD

**Issue by sid88in** [sid88in/serverless-appsync-plugin#71]

**Comment by sid88in** [comment]
At present, we have to create this user pool manually and then set configurations but CLI command should be able to create user pool if required (assuming credentials are set for creating the pool where this plugin is running).

**Comment by honkskillet** [comment]
@sid88in  Check out my post in #70.  I might be able to tackle this one instead.  From your comment above, are you saying that we'd have to use the aws-sdk to create the cognito user pool?  Any input pointing me in the right direction would be appreciated as I don't quite grok all the serverless code just yet.

**Comment by honkskillet** [comment]
BTW, you can create a cognito user pool (and also an identity pool) from the serverless.yml resources.  Add these lines to the end of your serverless.yml

```
resources:
  Resources:
    NewCognitoUserPool:
      Type: "AWS::Cognito::UserPool"
```
and then just run `serverless deploy`.
Documentation is here https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpool.html
The full properties list is ....
```
Type: "AWS::Cognito::UserPool"
Properties:
  AdminCreateUserConfig: 
    AdminCreateUserConfig
  AliasAttributes: 
    - String
  AutoVerifiedAttributes: 
    - String
  DeviceConfiguration: 
    DeviceConfiguration
  EmailConfiguration: 
    EmailConfiguration
  EmailVerificationMessage: String
  EmailVerificationSubject: String
  LambdaConfig: 
    LambdaConfig
  MfaConfiguration: String
  Policies: 
    Policies
  UserPoolName: String
  Schema: 
    - SchemaAttribute
  SmsAuthenticationMessage: String
  SmsConfiguration: 
    SmsConfiguration
  SmsVerificationMessage: String
  UserPoolTags: 
    String: String
```
Maybe it is best to leave the creation of the cognito user pool to the regular serverless library or some other CLI (like the AWS mobilehub cli).  Cognito user pool configurations can get complicated (with associated cognito identity pools and IAM roles for example).  @sid88in Thoughts?
