### ISSUE TITLE
Unable to get userPoolId from Ref

### ISSUE THREAD

**Issue by teddarling** [sid88in/serverless-appsync-plugin#82]
Currently under userPoolConfig.userPoolId a person must enter a string for the userPool. This is great if your developing just a single AppSync system without stages. However, if using stages, you may have different user pools.

It would be great if the plugin could use 
```
userPoolConfig:
  userPoolId:
    Ref: UserPool
```
to pull the user pool id from the resources.

**Comment by sid88in** [comment]
@teddarling want to take a stab at it? I am looking for more contributors :)

**Comment by honkskillet** [comment]
@teddarling Any progress?

**Comment by honkskillet** [comment]
@sid88in @teddarling Is this already covered by https://serverless.com/framework/docs/providers/aws/guide/variables/#nesting-variable-references ?

**Comment by honkskillet** [comment]
@teddarling  Maybe something like
```
provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}  ##get stage from cli options, otherwise default stage is dev
custom:
  userPoolId-dev: 123qwe
  userPoolId-production: 456ryt
  accountId: 454227793445 # replace this with your accountId
  appSync:
    name: myApi  
    apiId: asfasdfasdfasdf 
    authenticationType: AMAZON_COGNITO_USER_POOLS
    userPoolConfig: $(self:cutom.userPoolId-$(self:provider.stage))  ##<---OK to nest references
```

**Comment by teddarling** [comment]
That's kind of how I do it now.

```
custom:
  cognitoUserPoolId:
    dev: 'us-east-1_devKey'
    prod: 'us-east-1_prodKey'
  AppSyncApiId:
    dev: 'yyyyyyyyyy'
    prod: 'xxxxxxxxxxx'
  appSync:
    apiId: '${self:custom.AppSyncApiId.${self:provider.stage}}'
    authenticationType: AMAZON_COGNITO_USER_POOLS
    userPoolConfig:
      awsRegion: '${self:provider.region}'
      defaultAction: 'ALLOW'
      userPoolId: '${self:custom.cognitoUserPoolId.${self:provider.stage}}'

resources:
  Resources:
    UserPool:
      Type: "AWS::Cognito::UserPool"
      Properties:
        UserPoolName: '${self:custom.appName}-${self:provider.stage}-user-pool'
        ...

```

Based on the above, what I was hoping for was more like

```
authenticationType: AMAZON_COGNITO_USER_POOLS
    userPoolConfig:
      awsRegion: '${self:provider.region}'
      defaultAction: 'ALLOW'
      userPoolId: !Ref UserPool
```
or
```
authenticationType: AMAZON_COGNITO_USER_POOLS
    userPoolConfig:
      awsRegion: '${self:provider.region}'
      defaultAction: 'ALLOW'
      userPoolId: 
        Ref: UserPool
```

I honestly can't seem to find any sort of example where `Ref: ResourceName` appears under customs though, so I'm inclined to believe that a Ref call doesn't work there. I'm thinking that It's a matter of operation order and that the customs need to be set before resources so that they can be used. Otherwise it would appear that perhaps a circular reference type of error may occur.

I did just notice that it appears that we now have the ability to add AppSync using CloudFormation templates:
```
AWS::AppSync::ApiKey
AWS::AppSync::DataSource
AWS::AppSync::GraphQLApi
AWS::AppSync::GraphQLSchema
AWS::AppSync::Resolver
```

Which may mean that we no longer need to use a plugin to work with AppSync and Ref should work with those.

I'm going to test those out (probably in a few days) to see how well they work within the resources section as it doesn't appear that how I want it to work will.
